### ISSUE TITLE
Example Playgrounds don't work

### ISSUE THREAD

**Issue by LeanderG** [storyblok/storyblok-react#1061]
### Description

The examples playground-next, playground-next13-live-editing, playground-next13-rsc don't build.
Running `npm run build` in the playgrounds throws various errors.

### Suggested solution or improvement

One issue is described here but not fixed: https://github.com/storyblok/storyblok-react/issues/931
I tried to make a PR but couldn't due to unfixable linting errors.
I suggest running `npm run build` for all playgrounds in Github Actions to verify that everything works.

### Validations

- [X] Follow our [Code of Conduct](https://www.storyblok.com/trust-center#code-of-conduct?utm_source=github.com&utm_medium=readme&utm_campaign=storyblok-js-client)

**Comment by edodusi** [comment]
Closing as we refactored the playgrounds after v4
