### ISSUE TITLE
Does The Preview Mode Unmount Components When Data Changes?

### ISSUE THREAD

**Issue by fweth** [storyblok/storyblok-react#111]
Hello, I just edited the text because I could narrow down my problem.

I need one component which always render in the `_app.js` (some kind of background).  Since this background is an animation, in which I can scroll and move, I can tell if the component is only rerendered (with new data) or totally unmounted and remounted.  For some reason, if this is the *only* component in the `_app.js`, i.e. I don't do `<Component ...{pageProps}/>` at all, everything works perfect.  But as soon as another component is rendered on top, Storyblok either unmounts everything on each data change, or it just reloads the iFrame, I can't tell for sure.  Even just selecting elements (`storyblokEditable`) will restart everything.  Any ideas how to supress that?  I can see that for a few milliseconds, changing data even works with the preview, but then the reload / reset kicks in.

**Comment by fgiuliani** [comment]
Hey @fweth!

I see you had a discussion with @johannes-lindgren about this same issue on Discord, right?
Were you able to find a solution to the problem?
