### ISSUE TITLE
Bug in 1.0.9 - useStoryblokState preview param

### ISSUE THREAD

**Issue by annarhughes** [storyblok/storyblok-react#115]
There's a bug in a change made in 1.0.9, causing `useStoryblokState` to break when using `preview` param.
- conditional loading the bridge if it's preview ([918a88e](https://github.com/storyblok/storyblok-react/commit/918a88e94202ae92a4eb9a4918a393d05d40a642))

Expected behaviour:
Calling `useStoryblokState(story, {}, true)` should enable the bridge as the preview param is true
Calling `useStoryblokState(story, {}, false)` should disable the bridge as the preview param is false

Current behaviour:
Calling `useStoryblokState(story, {}, true)` disables the bridge whilst the preview param is true
Calling `useStoryblokState(story, {}, false)` enables the bridge whilst the preview param is false

```
  if (preview) {
    return initialStory;
  }
```

should be 

```
  if (!preview) {
    return initialStory;
  }
```

**Comment by fgiuliani** [comment]
Hi @annarhughes! 
Thanks for identifying and reporting the issue! 

I just added a fix in this commit:

https://github.com/storyblok/storyblok-react/commit/5cd93d379a10d3961c13f9a2ae9d3f8895bd1310

Could you check if the behaviour is correct now?

**Comment by annarhughes** [comment]
@fgiuliani Yes the preview param works as expected now!
Thanks for fixing so quickly 🙌
