### ISSUE TITLE
storyblok-v2-latest does not load

### ISSUE THREAD

**Issue by grantspilsbury** [storyblok/storyblok-react#1171]
### Describe the issue you're facing

**I am trying to get live editing to work within the Storyblok editor but the latest script isn't loaded.** 

When viewing the networks tab, when on a draft url (eg https://localhost:3010/api/draft?secret=foo&slug=pages/) within the Storyblok preview screen, I do not see `//app.storyblok.com/f/storyblok-v2-latest.js` being loaded. I assume the live editing is not working because of this. Why is my storyblok script not being loaded? 

I can see the cookies:
![Screenshot 2024-07-31 at 12 31 45 PM](https://github.com/user-attachments/assets/805ce129-30f3-47ec-a096-15059163a6d8)

And the HTML includes the Storyblok data-blok-c
`<div data-blok-c="{"name":"card_box","space":"6","uid":"6c0b3fa2-b9f1-4dcb-afb7-20259d65","id":"11923"}" data-blok-uid="119238130-6c0b3fa2-b9f1-4dcb-afb7-20259d65">`

The story has the _editable field
`_editable: ''
`

**I think my set up is correct (as it was working previously) so what could be the reason for the script not loading? What can I do to debug this? Everything seems pretty standard so I'm not sure why the file isn't loading. Maybe something to do with server components?**

My code set up:
```
// src/app/layout.tsx
import React from 'react'
import { storyblokInit, apiPlugin } from '@storyblok/react/rsc'
import StoryblokProvider from 'components/StoryblokProvider'

storyblokInit({
  accessToken: config.storyblokApiKey,
  use: [apiPlugin],
  apiOptions: {
    cache: {
      clear: 'auto',
      type: 'memory'
    }
  }
})

const RootLayout: React.FC<Props> = async ({ children }) => {
  return (
    <StoryblokProvider>
      <html lang="en" translate="no">
        <head>
          <GTMHeadScript />
        </head>
        <body>
          <GTMBodyScript />
          <ErrorBoundary>
            {children}
          </ErrorBoundary>
        </body>
      </html>
    </StoryblokProvider>
  )
}

// src/components/StoryblokProvider.tsx
'use client'

import { storyblokInit, apiPlugin } from '@storyblok/react/rsc'

storyblokInit({
  accessToken: config.storyblokApiKey,
  components: {
  body_copy: BodyCopy,
},
  use: [apiPlugin],
  apiOptions: {
    cache: {
      clear: 'auto',
      type: 'memory'
    }
  },
})

export default function StoryblokProvider({ children }: Props) {
  return children
}

// src/storyblok/remote.ts
import { getStoryblokApi, storyblokInit, apiPlugin } from '@storyblok/react/rsc'

storyblokInit({
  accessToken: config.storyblokApiKey,
  use: [apiPlugin],
})

export const getStoryBySlug = async <T>(
  slug: string,
  preview?: boolean,
  options?: Object
): Promise<Story<T> | null> => {
  const params = {
    version: 'draft',
    cv: Date.now(),
    ...options
  } as const
  try {
    const storyblokApi = getStoryblokApi()
    const cacheOption = preview ? { cache: 'no-store' as RequestCache } : {}
    const { data } = await storyblokApi.get(`cdn/stories/${slug}`, params, cacheOption)
    return data.story
  } catch (err: any) {
    console.error(JSON.stringify(err))
    return null
  }
}
```

### Reproduction

https://stackblitz.com/edit/stackblitz-starters-uh3eae?file=app%2Fapi%2Fdraft%2Froute.js

### System Info

```shell
Nextjs 14 app router app with some server and some client components
"storyblok-js-client": "^6.8.1",
"@storyblok/react": "^3.0.10",
```

### Used Package Manager

npm

### Validations

- [X] Follow our [Code of Conduct](https://www.storyblok.com/trust-center#code-of-conduct?utm_source=github.com&utm_medium=readme&utm_campaign=storyblok-js-client)

**Comment by alexjoverm** [comment]
Thanks for opening the issue @grantspilsbury! It's weird the bridge is not loading, as in a quick look, I see the SDK being initialized correctly in a client component.

We're going to investigate it further!

**Comment by grantspilsbury** [comment]
> Thanks for opening the issue @grantspilsbury! It's weird the bridge is not loading, as in a quick look, I see the SDK being initialized correctly in a client component.
> 
> We're going to investigate it further!

Thank you!

**Comment by arorachakit** [comment]
Hey @grantspilsbury ! 
While redirecting or changing the location in the draft route file, the Storyblok params that are used for bridge are lost. 
You need to add those as well when you're redirecting and it should work :) 

Here is a small example -

```  
 return new Response(null, {
      status: 307,
      headers: {
        Location: `/${story.full_slug}/?${searchParams.toString()}`,
      },
    });

```

You can use the search params, convert those to string and append - and it should work.
Let me know how it goes :)

**Comment by grantspilsbury** [comment]
> Hey @grantspilsbury ! While redirecting or changing the location in the draft route file, the Storyblok params that are used for bridge are lost. You need to add those as well when you're redirecting and it should work :)
> 
> Here is a small example -
> 
> ```
>  return new Response(null, {
>       status: 307,
>       headers: {
>         Location: `/${story.full_slug}/?${searchParams.toString()}`,
>       },
>     });
> ```
> 
> You can use the search params, convert those to string and append - and it should work. Let me know how it goes :)

Thank you you absolute legend 🚀
