### ISSUE TITLE
Update @storyblok/js dependency

### ISSUE THREAD

**Issue by izorg** [storyblok/storyblok-react#1249]
### Description

Hello,

Thank you for your effort

Please update `@storyblok/js` dependency to avoid deprecation warning:
```
Warning ⚠️: The RichTextResolver class is deprecated and will be removed in the next major release. Please use the `@storyblok/richtext` package instead. https://github.com/storyblok/richtext/
```

### Suggested solution or improvement

Update `@storyblok/js` to latest version 3.1.6 (or at least 3.1.3 where warning is initially suppressed)

### Validations

- [X] Follow our [Code of Conduct](https://www.storyblok.com/trust-center#code-of-conduct?utm_source=github.com&utm_medium=readme&utm_campaign=storyblok-js-client)

**Comment by edodusi** [comment]
included in #1267
