### ISSUE TITLE
4.0.0 Bridge Issue with NextJS & SSR

### ISSUE THREAD

**Issue by richardtaylordawson** [storyblok/storyblok-react#1262]
### Describe the issue you're facing

I've recently converted our code to use the new 4.0.0 and swapped to fully server components instead of an old method that was SSR but client side for all things Storyblok in order to keep visual editing.

After doing so, when you go to a page in Storyblok, the bridge doesn't immediately load like it used to. It used to pull up the page and show the boxes/borders around elements. Instead it takes awhile after editing for those to finally show up

### Reproduction

N/A

### System Info

```shell
N/A
```

### Used Package Manager

npm

### Validations

- [X] Follow our [Code of Conduct](https://www.storyblok.com/trust-center#code-of-conduct?utm_source=github.com&utm_medium=readme&utm_campaign=storyblok-js-client)

**Comment by edodusi** [comment]
@richardtaylordawson thanks for reporting, we will check asap

**Comment by arorachakit** [comment]
Hey @richardtaylordawson  - can you confirm that you're using the preview token and not the public token?

**Comment by richardtaylordawson** [comment]
@arorachakit it uses the public token since this is a production build. Is that incorrect? Should the preview url be a beta url? Just seems weird to me because then an editor isn't seeing exactly what they would see in production when they publish

**Comment by arorachakit** [comment]
Hey @richardtaylordawson ! 
Inside the visual editor, you should use the preview token - in this way the editor would exactly know how the draft content looks like before hitting publish. I could be a beta URL or same one with different settings to view draft content. 

Using draft content which is accessed by preview token is necessary to use. The way live editing works is - if you see two different JSONs, there is another key that comes along with the draft content , `editable` this allows the bridge to identify the components. 

If you use published content - this won't be sent along with the JSON. And hence once you make the change, the sdk will replace the content with draft content and then the editables will be in the place. That is why you don't see those on load and later on. 

Please try it with the draft content once, and let us know if you still don't see it working as expected :) 
Just to mention, bridge is meant to work with draft content only as you would load draft content inside the visual editor for people working on content to see draft (updated) content all the time :) 

Looking forward to your response!

cc - @edodusi @arpitbatra123

**Comment by richardtaylordawson** [comment]
@arorachakit awesome! Switching the token seems to have worked. We can close this and I'll reopen or start something new if I find it's being funky in any way! Thank you for the quick responses!

**Comment by arorachakit** [comment]
Awesome, let us know if anything else comes up!

**Comment by edodusi** [comment]
I'm glad we were able to help you @richardtaylordawson! And thanks @arorachakit for the nice catch 👍
