### ISSUE TITLE
Move "next" to peer dependencies

### ISSUE THREAD

**Issue by Thanaen** [storyblok/storyblok-react#1274]
### Description

Currently, if you want to use this library with Remix or Vite, the “next” dependency is systematically installed.

### Suggested solution or improvement

Marking “next” as a peer-dependency could solve the problem.

### Validations

- [X] Follow our [Code of Conduct](https://www.storyblok.com/trust-center#code-of-conduct?utm_source=github.com&utm_medium=readme&utm_campaign=storyblok-js-client)

**Comment by edodusi** [comment]
@Thanaen thanks for this suggestion, I included it in #1267 and it's already released, if you could give me some feedback when you upgrade I would really appreciate
