### ISSUE TITLE
[Docs/Question] What is the current alternative for react v17 (Next.js) users.

### ISSUE THREAD

**Issue by madebyfabian** [storyblok/storyblok-react#129]
Hello there, 
I was first excited to see a react library that is providing less boilerplate.
I am currently not able to upgrade to React v18 due to other Dependencies not working with it. 
I was therefore curious about what is the current most modern alternative way of creating a nextjs site with full storyblok support? I currently implemented storyblok on my nextjs page, but facing some issues because many things are implemented by myself. I am using

- "@storyblok/storyblok-editable": "^1.1.0"
- "storyblok-js-client": "^4.2.0"
- "storyblok-rich-text-react-renderer": "^2.5.2"

currently. Is this the best current way when you are not able to upgrade to React v18 and use this package?

**Comment by fgiuliani** [comment]
Hey @madebyfabian thank you for your message.

You should be able to use a previous version of `@storyblok/react` on your React v17 project. The version 1.0.6 should work with React v17.

Could you try it and see if that works for you? With it, you wouldn't need to install `@storyblok/storyblok-editable` or `storyblok-js-client` (you will still need `storyblok-rich-text-react-renderer`)

**Comment by fgiuliani** [comment]
hey @madebyfabian were you able to take a look?

**Comment by madebyfabian** [comment]
Hey @fgiuliani 
Thanks for your comment and getting back. I was on holidays, so apologies for the late response.

My current React 17 setup now looks like:

- "@storyblok/js": "^1.6.1",
- "storyblok-rich-text-react-renderer": "^2.5.2",

And I have written some helpers to get `@storyblok/js` running in React 17:

```ts
import { useState } from 'react'
import getConfig from 'next/config'
import { storyblokInit, apiPlugin, StoryData, useStoryblokBridge as _useStoryblokBridge } from '@storyblok/js'
export type { StoryData } from '@storyblok/js'

const isStoryblokPreviewMode = !getConfig().publicRuntimeConfig.isProduction

export const { storyblokApi } = storyblokInit({
	accessToken: process.env.NEXT_PUBLIC_STORYBLOK_TOKEN,
	use: [apiPlugin],
	bridge: isStoryblokPreviewMode,
})

export type GetStoryResult = null | StoryData

// When replacing @storyblok/js with @storyblok/react later, this function will be removed
export const useStoryblokBridge = (originalStory: GetStoryResult) => {
	const [story, setStory] = useState<StoryData>(originalStory || ({} as StoryData))
	if (!storyblokApi) {
		console.error("You can't use useStoryblok if you're not loading apiPlugin.")
		return null
	}

	if (isStoryblokPreviewMode) _useStoryblokBridge(story.id, story => setStory(story), { preventClicks: true })

	return story
}
```

and usage example `pages/index.tsx`:
```ts
import type { FC } from 'react'
import { useStoryblokBridge, GetStoryResult } from '@/lib/storyblok'

type Props = {
	story: GetStoryResult
}

const Home: FC<Props> = ({
	story,
}) => {
	story = useStoryblokBridge(story)

	return (
		<div>
			{/* use story data here */}
		</div>
	)
}

export default Home
```

I did not try out the `1.0.6` version, didn't knew it would work in React 17. Will try it out maybe. But since I saw the existing issues here https://github.com/storyblok/storyblok-react/issues/112, I think I will stick to my current solution. 

Closed this since it's resolved, people can either use their own implementation of `@storyblok/js` just like I did, or use `1.0.6` version.
