### ISSUE TITLE
Live-editing with Next.js 15 on Vercel

### ISSUE THREAD

**Issue by peperoli** [storyblok/storyblok-react#1295]
### Describe the issue you're facing

I closely followed the described setup process for Next.js App Router with RSC (really happy about the improved README btw) and live-editing is working perfectly on a local environment. But when I deploy the app to Vercel, the dotted boxes are gone and data only gets updated when hard refreshing the visual editor preview.

I made sure that all routes are rendered dynamically, when fetching data from Storyblok, the preview token is used,  `version` is set to `draft` and `cv` is `Date.now()`. What conditions should be met to enable live-editing? Am I missing something obvious here?

### Reproduction

-

### System Info

```shell
node: 18.19.0
next.js: 15.0.1
@storyblok/react: 4.0.0
```

### Used Package Manager

yarn

### Validations

- [X] Follow our [Code of Conduct](https://www.storyblok.com/trust-center#code-of-conduct?utm_source=github.com&utm_medium=readme&utm_campaign=storyblok-js-client)

**Comment by edodusi** [comment]
Hi @peperoli, how is the app running on the deployment? Is it configured for SSR?

**Comment by peperoli** [comment]
> Hi @peperoli, how is the app running on the deployment? Is it configured for SSR?

Generally no, but inside the visual editor, the app enables [draft mode](https://nextjs.org/docs/app/building-your-application/configuring/draft-mode) to switch to dynamic rendering.

**Comment by edodusi** [comment]
@peperoli the only thing I can think of is some configuration issue on Vercel, if the local env work then the live preview is configured correctly and should work

**Comment by peperoli** [comment]
@edodusi yeah, makes sense to me. I'm going to do some more research about my Vercel configuration.

**Comment by edodusi** [comment]
ok @peperoli let me know if you find something that we can add to the doc

**Comment by peperoli** [comment]
Alrighty I promptly found the issue. I'm using an api route to enable draft mode and then redirect to the actual slug. I forgot to pass the search params to the redirect URL which are needed to initialize Storyblok bridge. There's even a hint in the docs: https://www.storyblok.com/docs/guide/essentials/visual-editor#additional-query-params

```ts
// api/draft/route.ts

import { draftMode } from 'next/headers'
import { redirect } from 'next/navigation'
import StoryblokClient from 'storyblok-js-client'

export async function GET(request: Request) {
  const { searchParams } = new URL(request.url)
  const slug = searchParams.get('slug')

  const storyblok = new StoryblokClient({ accessToken: process.env.STORYBLOK_TOKEN })
  const { data } = await storyblok.get(`cdn/stories/${removeLocaleFromSlug(slug)}`, {
    version: 'draft',
    excluding_fields: 'header,body,seo',
  })

  if (!data?.story) {
    return new Response('Invalid slug', { status: 401 })
  }

  const draft = await draftMode()
  draft.enable()

  // Redirect to the path from the fetched story,
  // pass the search parameters to initialize Storyblok bridge
  redirect(`/${data.story.full_slug}?${searchParams.toString()}`)
}
```
