### ISSUE TITLE
useStoryblokState language option

### ISSUE THREAD

**Issue by AlexHramovich** [storyblok/storyblok-react#130]
Hey!
Thanks for the React version, it looks good!

A quick quick question about locales logic. According to this article, we need to pass the locale to the hook, as in the example below. ([documentation article link](https://www.storyblok.com/tp/next-js-react-guide-old)).
```
...
 
export default function Page({ story, locale, locales, defaultLocale }) {
  story = useStoryblokState(story, {
    resolveRelations: ["featured-posts.posts", "selected-posts.posts"],
    language: locale,
  });
 
...
```

I tried to do this, but it seems `useStoryblockState` doesn't accept the `language` parameter at all, so I can't get a working preview in the CMS account.

I checked the types and see that we can only pass these options

```
export interface StoryblokBridgeConfigV2 {
    resolveRelations?: [string];
    customParent?: string;
    preventClicks?: boolean;
}
```

Could you please share with us the correct way to implement it?
I can't find any documents or updates related to this issue.

Thanks!

**Comment by fgiuliani** [comment]
Hey @AlexHramovich thank you very much for reporting this issue. Looks like we forgot to add the `language` parameter to the `StoryblokBridgeConfigV2` interface when adding TypeScript support to the SDKs.

If you want to add it, you can go ahead and create a PR with the change here 🙂
https://github.com/storyblok/storyblok-js/blob/e6e4522e72309e7c67d8495859202cbad269475b/lib/types.ts#L34

If not, we will take care of that soon.
Thank you!

cc @alexjoverm

**Comment by fgiuliani** [comment]
Hey @AlexHramovich I created this PR adding the parameter to the type definition. Once it's merged, you should be able to define a locale for the stories:

https://github.com/storyblok/storyblok-js/pull/102
