### ISSUE TITLE
Make baseUrl of the storyblokapiclient configurable

### ISSUE THREAD

**Issue by ZronekM** [storyblok/storyblok-react#131]
In our setup we use an API gateway directly below the frontend which handles circuit breaking, alerting, authentication, session handling etc.

Unfortunately it is not possible to change the baseurl which should point to the API-gateway or configure it in the `storyblokInit` call. It is possible to change the hostname with a configuration like that
```
apiOptions: {
          proxy: {
              host: "mydomain.com"
              port: 1234
          }
      }
```

but we would require the url to go to `mydomain.com/webapi`.

**Comment by ZronekM** [comment]
The API queries should go through the API Gateway before hitting storyblok.
So the flow should look something like this:

- client makes a request against mydomain.com/webapi/cms/:slug_id
- the apigateway has a route defined which says that it should redirect form /webapi/cms/:slug_id to api.storyblok.com/v1/cdn/stories/:slug_id

The apiplugin does only support rewriting the hostname.

**Comment by fgiuliani** [comment]
Hey @ZronekM. If I understand correctly, you should init the storyblokInit connection, and use the API client, in your API-gateway. As that's where you are actually calling the Storyblok API. Are you having an issue with that?

Why would you use the API client in the frontend of your application, if the layer that is actually calling the Storyblok API is the API-gateway?

**Comment by ZronekM** [comment]
Hey @fgiuliani ,
sorry for the late reply.

> If I understand correctly, you should init the storyblokInit connection, and use the API client, in your API-gateway.

This is what we are currently doing. We implemented a separate route with axios that is then rewritten in the API-gateway.
The api-gateway just replaces the baseurl (and some minor path'). 

It though is a bit sad then that we have to implement all routes ourselves (e.g. get by single slug, get space version, ...) which is all done conveniently in your client here. We also probably miss out some optimization which you might have done (or might come in the future). All which would be needed is to change the baseurl. The hostname can already be changed.

**Comment by fgiuliani** [comment]
Hey @ZronekM sorry. I talked to the DevRel team about your issue and looks like there is already a way of making this work:

```
storyblokInit({
  accessToken: "lalaa",
  apiOptions: {
    endpoint: "https://mydomain.com"
  }
})
```

Could you check if this works for you?

**Comment by ZronekM** [comment]
Hey @fgiuliani ,

it doesnt seem to work for me. 
It isn't even typed in your library, see -> https://github.com/storyblok/storyblok-js-client/blob/master/types/index.d.ts#L60-L74

**Comment by fgiuliani** [comment]
Hey @ZronekM you are right, that's not typed in the package. It should be added to the types in `storyblok-js-client`

Here is the code where that parameter is used:
https://github.com/storyblok/storyblok-js-client/blob/master/source/index.js#L58

And it's briefly mentioned in the README:
https://github.com/storyblok/storyblok-js-client/#documentation

Not sure if the behavior of that parameter is what you are actually needing

**Comment by ZronekM** [comment]
alright, thanks for you help!
