### ISSUE TITLE
useStoryblokState loses Type data

### ISSUE THREAD

**Issue by breningham** [storyblok/storyblok-react#133]
if you currently pass a typed story (e.g `StoryData<SomeContentType>`) the type that is returned is a simple StoryData - meaning that in typescript we need to narrow the type or cast it . 

it would be better if the useStoryBlokState fn inferred the Type from the input type, this can be as simple as 

```ts

const useStoryblokState = <Content extends StoryblokComponent<string>>((
  initialStory: StoryData = {} as StoryData<Content>,
  bridgeOptions: StoryblokBridgeConfigV2 = {},
  preview: boolean = true
): StoryData<Content> ) => /** implementation **/

```

I can create a PR if you like.

**Comment by fgiuliani** [comment]
Hey @breningham thank you very much for the input.

If you want, and you can, create a PR with the changes, that would be super helpful. Feel free to do it 😃

**Comment by fgiuliani** [comment]
A similar PR was created for `useStoryblokBridge` here:

https://github.com/storyblok/storyblok-js/pull/88

**Comment by fgiuliani** [comment]
Hey @breningham I created a PR adding some changes to fix the issue you detailed here:

https://github.com/storyblok/storyblok-react/pull/164
