### ISSUE TITLE
Unable to resolve relations

### ISSUE THREAD

**Issue by breningham** [storyblok/storyblok-react#134]
Hi im in the middle of moving us from the older storyblok-react + a home-grown useStorybook hook over to using this library. 

we are using NextJS w/ Typescript  and get the Story/Stories in a `getStaticProps` function so i have been using the `useStorybookState` hook which for the most part works fine, until we get to relations resolution. 

in the getStaticProps function we set `sbParams.resolve_relations = 'ArticleTemplate.relatedJargon'` before making the request. and previously this has worked with the old hook, however now it simply throws an Error: `Error - TypeError: Cannot create property 'filename' on string 'ArticleTemplate.relatedJargon'` 

meaning that all of the jargon pages now fail to build. 

Versions: 
Next: 12.1.1
@storyblok/react: 1.0.12
storyblok-js-client: 4.5.6

**Comment by kb1995** [comment]
I'm in the exact same situation and it seems like this is a related issue to this - https://github.com/storyblok/storyblok-js-client/issues/213

**Comment by breningham** [comment]
After diving deeper into this,i believe the issue is resolved in storyblok-js-client 4.5.6 HOWEVER `@storyblok/react` bundles `@storyblok/js` which also bundles version 4.5.2 of `storyblok-js-client` so no matter what version of any of those packages you install it does not matter.  

i have created some PRs to stop the bundling: 
https://github.com/storyblok/storyblok-js/pull/82 & https://github.com/storyblok/storyblok-react/pull/136

**Comment by kb1995** [comment]
Thanks @breningham, this seems to be the solution!

Just a note that I tested `resolve_links` but it doesn't work as well. Looking at the [codebase](https://github.com/storyblok/storyblok-js-client/blob/b5036135a047f478095e0d654562613db40db813/source/index.js) it looks like the logic between the two params is quite similar

**Comment by fgiuliani** [comment]
Hello @breningham and @kb1995 thanks for your comment.

Instead of stopping bundling `storyblok-js-client`, another option would be to update the version of `storyblok-js-client` used in `@storyblok/js`. What do you think?

**Comment by breningham** [comment]
well, the problem with bundling is that any update to any of packages would require a manual bump with the latest code. 

or you could just set them as dependencies (which i think currently, they are both bundled and listed as dependencies) and decouple the releases. 

IMO it only makes sense to bundle when you have the infrastructure in place to automate that version bump, otherwise it is much simpler and less error prone to simply release the packages completely separately linked as dependencies. 

another problem with the current approach is that, as i mentioned earlier, you currently bundle @storyblok/js and set it as a depndency, meaning that you have allot of duplication going on - when you install @storyblok/react, you are essentially installing @storyblok/js twice, and storyblok-js-client 3 times. this is obviously only a superficial problem.

**Comment by fgiuliani** [comment]
Hey @breningham about the original issue that you reported, @alexjoverm created this PR on the `@storyblok/js` repository that should help:

https://github.com/storyblok/storyblok-js/pull/90

**Comment by fgiuliani** [comment]
@breningham thanks for testing and checking.

About the bundling, we're still discussing that with the DevRel team. We may want to keep bundling `@storyblok/js`. Will keep you posted about that.

cc @alexjoverm

**Comment by kb1995** [comment]
@fgiuliani Am I doing something wrong here? Even after I upgraded the package to `^1.0.14`, neither resolve_relations or resolve_links are working:

```
  let slug = params.slug;

  let sbParams = {
    version: "published", // 'draft' or 'published'
    resolve_relations: ["authors.author"],
    resolve_links: "story",
  };

  const storyblokApi = getStoryblokApi();
  let { data } = await storyblokApi.get(`cdn/stories/blog/${slug}`, sbParams);
```

This outputs the following object

```
{
    "_uid": "f0cb3968-571a-46ae-8598-1bbae99ee1a0",
    "image": "",
    "title": "",
    "author": "3272ff27-7e6b-4a83-8f54-bdc6aa976131",
    "authors": [
        "3272ff27-7e6b-4a83-8f54-bdc6aa976131"
    ],
    "component": "Blog Post",
    "rich_text": [
        {
            "_uid": "3f5f891d-84bd-4042-8827-1ea7c2c66b9c",
            "link": {
                "id": "7bb734e1-699b-43d2-b88f-a5119ce164e5",
                "url": "",
                "anchor": "test-anchor",
                "linktype": "story",
                "cached_url": "home"
            },
            "text": "Hello",
            "component": "Button"
        },
        {
            "_uid": "84338f5c-59bf-45fb-946c-e8625e839978",
            "link": {
                "id": "",
                "url": "https://www.google.com/",
                "linktype": "url",
                "cached_url": "https://www.google.com/"
            },
            "text": "External Link",
            "component": "Button"
        }
    ]
}
````

**Comment by fgiuliani** [comment]
hey @kb1995 could you show, with a screenshot, how that story looks like in the Storyblok app?

Do you have a block named "authors" with a property called "author"? Because that's not what I see on the JSON that you shared

**Comment by kb1995** [comment]
@fgiuliani Screenshot below. Note that I'm pretty new to Storyblok so maybe I've misunderstood the docs

<img width="1134" alt="Screenshot 2022-07-22 at 09 29 25" src="https://user-images.githubusercontent.com/32920882/180398225-07d5d5b0-c65a-4480-a7a2-4030abfe3f3c.png">

**Comment by fgiuliani** [comment]
@kb1995 have you tried with

```
  let sbParams = {
    version: "published", // 'draft' or 'published'
    resolve_relations: ["authors"],
    resolve_links: "story",
  };
```

**Comment by kb1995** [comment]
@fgiuliani Thanks for the suggestion, but this doesn't work as well. Can you share a working example where resolve_relations is being used?

**Comment by tcrisseapp** [comment]
@fgiuliani Thanks for sharing! I'm facing the exact same issue. I've followed the article as described above but I'm not able to resolve the relations using the react SDK (1.3.3) (It only retrieves the uuid). 

Using the API however it is able to resolve with the exact same relation.

Works: `/v1/cdn/stories/home?token={{ _.token }}&version=draft&resolve_relations=header` 
Doesn't work:  
```  
let sbParams = {
    version: "draft",
    resolve_relations: ["header"],
  };

const storyblokApi = getStoryblokApi();
let { data } = await storyblokApi.get(`cdn/stories/${slug}`, sbParams);
```

**Comment by marekmaurizio** [comment]
Is this still a problem? 
Using &resolve_relations=authors paramter when calling the API works for me, but 

`let sbParams = {
    version: "draft",
    resolve_relations: ["authors"],
  };`

Does not. Is the fundamental get function used in all the tutorials still bugged?!

**Comment by fgiuliani** [comment]
Hi @marekmaurizio this should be working as expected 🤔 

What's the content structure in your space? Can you share an example so I try to replicate it?
Are you using the latest version of the React SDK?
