### ISSUE TITLE
Is 0.1.0 version correctly released to npm?

### ISSUE THREAD

**Issue by dohomi** [storyblok/storyblok-react#15]
Hello,

I bumped into the issue that the component is not correctly wrapped. I know that https://github.com/storyblok/storyblok-react/pull/12 is merged, but it seems that npm v0.1.0 still throws an error.

If I inspect the code of https://github.com/storyblok/storyblok-react/blob/master/src/sb-editable.jsx#L24 The code is still old.

Did maybe something went wrong in the release to publish the changes?

**Comment by emanuelgsouza** [comment]
Hi! This issue was fixed in the last release - [v0.1.1](https://github.com/storyblok/storyblok-react/releases/tag/v0.1.1). Take a look!
