### ISSUE TITLE
List `axios` as peer dependency

### ISSUE THREAD

**Issue by KinnersleyM** [storyblok/storyblok-react#154]
Starting a new next.js project with `@storyblok/react` and running `yarn dev` results in the following error:

```
wait  - compiling...
error - ./node_modules/@storyblok/react/dist/storyblok-react.mjs:30:0
Module not found: Can't resolve 'axios'
```

I suspect this is because this package depends on `storyblok-js` which then depends on `storyblok-js-client` which requires `axios` as a peer dependency. All of these packages should probably list `axios` as a `peerDependency` in their `package.json` along with updating their `README.md` installation instructions.

**Comment by fgiuliani** [comment]
Hey @KinnersleyM! Thanks for your message, and for the PR that you created. Really appreciate your willingness to contribute to the SDK.

Right now, the Storyblok team is working on removing `axios` from the `storyblok-js-client` (and `storyblok-js`, and `storyblok-react`). We are doing the final test of a new version of `storyblok-js-client`, where we don't need `axios` anymore.

Let us evaluate if it makes sense to add the dependency right now, or if it's better to wait for the new version of `storyblok-js-client` to be released.

cc @thiagosaife @alexjoverm

**Comment by fgiuliani** [comment]
Thanks for contributing @KinnersleyM!
