### ISSUE TITLE
`useStoryblokBridge` should not be used as a react hook

### ISSUE THREAD

**Issue by wolkyura** [storyblok/storyblok-react#163]
Hello! I've recently changed `storyblok-js-client` library (with the custom solution for making bridge work) with `@storyblok/react`, and I noticed some performance issues:

https://user-images.githubusercontent.com/54850073/182087992-c270aa75-aa39-462b-86b5-153ff8fa7bf3.mp4

After some investigation, I've noticed that `useStoryblokBridge` is used as a React hook in `@storyblok/react`, and also this hook is exported from `@storyblok/js` library.

[`storyblok-react/lib/index.ts (line 17):`](https://github.com/storyblok/storyblok-react/blob/feature/v1/lib/index.ts#L17)
```js
export {
  storyblokEditable,
  apiPlugin,
  useStoryblokBridge,
} from "@storyblok/js";
```

[`storyblok-react/lib/index.ts (line 56):`](https://github.com/storyblok/storyblok-react/blob/feature/v1/lib/index.ts#L56)
```js
export const useStoryblokState = (
  initialStory: StoryData = {} as StoryData,
  bridgeOptions: StoryblokBridgeConfigV2 = {},
  preview: boolean = true
): StoryData => {
  let [story, setStory] = useState<StoryData>(initialStory);

  if (!preview) {
    return initialStory;
  }

  useSbBridge(story.id, (newStory) => setStory(newStory), bridgeOptions);

  useEffect(() => {
    setStory(initialStory);
  }, [initialStory]);

  return story;
};
```

But the problem here is that it's not actually React hook, I mean it can't be used inside the component body as a hook, it has event registration inside that would be calling on every render change, correct me if I'm wrong:

[`storyblok-js/lib/index.ts (line 18):`](https://github.com/storyblok/storyblok-js/blob/main/lib/index.ts#L18)
```js
export const useStoryblokBridge = <T extends StoryblokComponentType<string> = any>(
  id: Number,
  cb: (newStory: StoryData<T>) => void,
  options: StoryblokBridgeConfigV2 = {}
) => {
  if (typeof window === "undefined") {
    return;
  }

  if (typeof window.storyblokRegisterEvent === "undefined") {
    console.error(
      "Storyblok Bridge is disabled. Please enable it to use it. Read https://github.com/storyblok/storyblok-js"
    );

    return;
  }

  if (!id) {
    console.warn("Story ID is not defined. Please provide a valid ID.");
    return;
  }

  window.storyblokRegisterEvent(() => {
    const sbBridge: StoryblokBridgeV2 = new window.StoryblokBridge(options);
    sbBridge.on(["input", "published", "change"], (event) => {
      if (event.action == "input" && event.story.id === id) {
        cb(event.story);
      } else {
        window.location.reload();
      }
    });
  });
};
```

Possible solutions:
1. Rename `useStoryblokBridge` to `registerBridge` and use it only on mount (`React.useEffect(() => {}, [])`) OR
2. Create __React__ hook `useStoryblokBridge` and call register event function only once on mount (`React.useEffect(() => {}, [])`)

**Comment by wiledal** [comment]
It's my observation that the Storyblok team most likely does not use React (being centrally Vue-based), so the @storyblok/js repository was designed without React in mind, and this extension is implemented with lacking React experience.

In fact, @storyblok/js also lacks the functionality needed for automatically excluding and including the bridge based on editor context, and  the non-hook `useStoryblokBridge`, used in `useStoryblokState`, throws errors in all scenarios except within the editor.

Your solution above is nice, however it does not allow us to conditionally use the bridge without warnings. It'd be great to use the bridge if available, and ignore it if it is not.

https://github.com/storyblok/storyblok-react/issues/156

**Comment by fgiuliani** [comment]
Hello @wolkyura!
I created this PR renaming useStoryblokBridge:
https://github.com/storyblok/storyblok-react/pull/225

Whenever you have the chance, please let me know what you think.
