### ISSUE TITLE
Components could be less Storyblok dependent

### ISSUE THREAD

**Issue by sendy34** [storyblok/storyblok-react#171]
Right now, using `storyblokEditable` hook, we are able to make components editable via Visual Editor which is amazing.
But this makes components dependent on Storyblok, however, the same components could be hardcoded somewhere else in the application as well.

We could created dedicated abstractions for Storyblok, but with previous approaches we were able to make standard react components work with Storyblok without any change in code.

For example, with this package, we are forced to use `blok` prop on our components.

With a custom Component loop, we were able to use `<SbEditable>` on top of all the child components.
This way, we never needed `blok` prop and properties coming from Storyblok were being directly passed to the component without `blok` namespace. This way, any react component was easy to export to Storyblok without any code changes.

Here is a code snippet which we used previously to define component loop.
Notice we are extracting editable props out and passing to <SbEditable> and rest of the props are being passed to the actual component.

```
const DynamicComponent: React.FC<DynamicComponentProps> = ({
  blok = {},
  ...additionalProps
}) => {
  const { _uid, component, _editable, ...props } = blok
  if (typeof Components[blok.component] !== 'undefined') {
    const Component = Components[blok.component]
    return (
      <SbEditable key={blok._uid} content={{ ...blok }}>
        <Component {...additionalProps} key={blok._id} {...props} />
      </SbEditable>
    )
  }

  return (
    <SbEditable key={blok._uid} content={blok}>
      <Placeholder componentName={blok.component} />
    </SbEditable>
  )
}
```

If we can have some way in this package where we can implement a custom iterator for Component loop, and with the help of `<SbEditable>` wrapper, we could define a custom Component iterator which would remove dependency from `blok` prop.

Thanks!

**Comment by fgiuliani** [comment]
Hi @sendy34! Thank you for your message and suggestion.

The `SbEditable` component was removed some time ago, because of issues related to `findDOMNode`:
https://github.com/storyblok/storyblok-react/issues/19

Do you have any idea or proposal on how could your approach be covered by the React SDK?

**Comment by sendy34** [comment]
@fgiuliani Interesting! Yea agree. Without FindDomNode, achieving this is tricky!

**Comment by samlof** [comment]
I make wrapper components around components for storyblok. The wrapper adds the sbeditable and parses the inputs from blok
