### ISSUE TITLE
findDOMNode is deprecated in StrictMode

### ISSUE THREAD

**Issue by rokinsky** [storyblok/storyblok-react#19]
I receive a warning in the strict mode due to this: https://github.com/storyblok/storyblok-react/blob/master/src/sb-editable.jsx#L23

Warning: findDOMNode is deprecated in StrictMode. findDOMNode was passed an instance of SbEditable which is inside StrictMode. Instead, add a ref directly to the element you want to reference. Learn more about using refs safely here: https://reactjs.org/link/strict-mode-find-node

**Comment by onefriendaday** [comment]
This plugin will be replaced by an universal plugin that works for more frameworks soon.
In the meantime you can use following function to add Storyblok's editmode to the elements of your choice:

```js
import React from 'react'
const Editable = (blok) => {
  if (typeof blok !== 'object' || typeof blok._editable === 'undefined') {
    return {}
  }

  const options = JSON.parse(blok._editable.replace(/^<!--#storyblok#/, '').replace(/-->$/, ''))

  return {
    'data-blok-c': JSON.stringify(options),
    'data-blok-uid': options.id + '-' + options.uid
  }
}

const Feature = ({ blok }) => (
    <div {...Editable(blok)} className="column feature">
      {blok.name}
    </div>
)

export default Feature
```
