### ISSUE TITLE
LICENSE file is missing

### ISSUE THREAD

**Issue by stschroeder** [storyblok/storyblok-react#193]
Hi there 👋.

I noticed that the source code currently does not contain a LICENSE file. Under which license is the code currently released? And could you please also add this information in the form of a LICENSE file to this repository?

See also [Adding a license to a repository](https://docs.github.com/en/communities/setting-up-your-project-for-healthy-contributions/adding-a-license-to-a-repository) and [package-json#license](https://docs.npmjs.com/cli/v8/configuring-npm/package-json#license).

Thanks in advance!

**Comment by colinhowe** [comment]
Giving this a bump. We're adopting Storyblok and the lack of a license here is creating a minor SOC2 headache for us.

**Comment by Barokai** [comment]
bumping this too, as i am curious about that. 
https://choosealicense.com/ by github could help to find the appropriate license

**Comment by nx-dennytrebbin** [comment]
To ensure compliance, our tools discovered no license for this project.
Unfortunately, end users interact with Storyblok and as such, the unlicensed code in question causes some trouble for us.

**Comment by nx-dennytrebbin** [comment]
The project's license was intended to be MIT, but the PR got closed (without comments) instead of merged.

https://github.com/storyblok/storyblok-react/pull/58

**Comment by dariusrosendahl** [comment]
@fgiuliani @phlipper Could somebody elaborate what the plan is? Would be nice to tell some larger clients that there's no license problem. :)

**Comment by richardtaylordawson** [comment]
Bumping this :)

**Comment by marckraw** [comment]
👍🏻

**Comment by dlhck** [comment]
@edodusi could you please take a look at this? I hope/assume this will be MIT licensed. For enterprise clients this is very important.

**Comment by edodusi** [comment]
@dlhck I will check ASAP, thanks for bringing this to my attention

**Comment by dlhck** [comment]
thanks @edodusi ! 👏🏼
