### ISSUE TITLE
Is hasClass that One Weird Trick I never learned?

### ISSUE THREAD

**Issue by programbo** [storyblok/storyblok-react#2]
I'm pretty confused about the use of the `hasClass` function in [sb-editable.jsx](https://github.com/storyblok/storyblok-react/blob/master/src/sb-editable.jsx#L27).

<img width="414" alt="warning" src="https://user-images.githubusercontent.com/1026196/42729656-6b6aea16-8811-11e8-86f4-e27e9d696293.png">

It hasn't actually caused an error for me because I use web browsers that support `classList`, but it's making my linter angry.

**Comment by onefriendaday** [comment]
You are right. Has been fixed in version 0.0.6. Thanks for the report!
