### ISSUE TITLE
resolve_relations not working with storyblok-react

### ISSUE THREAD

**Issue by neil-morgan** [storyblok/storyblok-react#20]
I'm getting a bug that seems to originate with `storyblok-react`

I am using resolve_relations and passing the same data to our "local" component and the storyblok editable component but when rendered in storyblok preview the data resolved by resolve_relations has been stripped out and only the uuid of the content is passed through.

Our components map.
```js
import SbEditable from "storyblok-react";
import authorable from "./authorable/";
import template from "./template/";

const ComponentsList = {
  ...authorable,
  ...template
};

const Components = props => {
  if (typeof ComponentsList[props.component] !== "undefined") {
    const Component = ComponentsList[props.component];

    return (
      <SbEditable content={props} key={props._uid}>
        <Component content={props} key={props._uid}>
          {props.children}
        </Component>
      </SbEditable>
    );
  }

  return <p>The component {props.component} has not been created yet.</p>;
};

export default Components;
```

The image shows the resulting data difference when console logging the specific component I am using resolve_relations for.
One version has the correct data, the other has had the resolve_relations data removed, returning only the uuid.

<img width="953" alt="Screenshot 2021-12-02 at 15 44 05" src="https://user-images.githubusercontent.com/52212097/144465722-3f352b7f-c277-4fe1-8e06-a2f532cb9c35.png">

Can anyone help guide me?

**Comment by jromme** [comment]
Would you care to share what fixed it for you? @neil-morgan
