### ISSUE TITLE
Real time visual editing issue with the React app

### ISSUE THREAD

**Issue by serrg** [storyblok/storyblok-react#213]
Hi there 👋 I am trying to setup some basic frontend app based on React and I have started playing with `@storyblok/react`

React playground which is available under https://github.com/storyblok/storyblok-react/tree/feature/v1/playground is not working with the Visual Editor properly, blocks are not highlighted and live changes are not applied in real time:

<img width="1234" alt="Screenshot 2022-09-01 at 12 30 24" src="https://user-images.githubusercontent.com/1391453/187897024-752ae910-ee10-42a1-b8e1-8a53000ffad4.png">

When I run the similar playground available for Vue https://github.com/storyblok/storyblok-vue/tree/main/playground it is all working properly by default:

<img width="1265" alt="Screenshot 2022-09-01 at 11 45 12" src="https://user-images.githubusercontent.com/1391453/187897148-6ee6d5f4-ab50-4fce-adb4-b5446b8688fd.png">

Space was created from the scratch with the default space creator (home page with feature/grid/teaser)

I was trying to setup React app from the scratch by installing `@storyblok/react` (with one simple text block in the space) and I was also unable to get visual editing working as expected.

**Comment by fgiuliani** [comment]
Hi @serrg! Sorry to hear that.

Could you take a look at this example repository, to see if it works properly?
https://github.com/storyblok/getting-started/tree/master/reactjs

Or this example in Stackblitz:
https://stackblitz.com/edit/getting-started-react

Or this other one, that is a Next.js project (Next.js is a React-based framework):
https://github.com/storyblok/getting-started/tree/master/nextjs

And let me know if the same is happening to you?

**Comment by serrg** [comment]
Hi @fgiuliani! Thanks for the fast answer, 

> Could you take a look at this example repository, to see if it works properly?
> https://github.com/storyblok/getting-started/tree/master/reactjs

I can confirm that this example is working excellent:

![Screenshot 2022-09-06 at 09 33 47](https://user-images.githubusercontent.com/1391453/188574622-a1da4190-e2e5-44af-92d9-23cb74be11aa.png)

BUT [getting-started](https://github.com/storyblok/getting-started/tree/master/reactjs) is using version `1.0.4`  and [storyblok-react/playground](https://github.com/storyblok/storyblok-react/tree/feature/v1/playground) is using `1.1.6` so it looks like there is something incompatible in the latest version. 

When I have tried to update the example from [getting-started](https://github.com/storyblok/getting-started/tree/master/reactjs) and upgrade `@storyblok/react` package to the latest version (`1.1.6`) is not working properly inside the visual editor (blocks are not highlighted and live changes are not applied):

![Screenshot 2022-09-06 at 09 52 23](https://user-images.githubusercontent.com/1391453/188578212-0d4ca195-debd-4bea-a7a5-f2cbff7ac938.png)

**Comment by serrg** [comment]
I have checked all the versions down from `1.1.6` and version `1.1.0` of the `@storyblok/react` is the latest version which is working with [storyblok-react/playground](https://github.com/storyblok/storyblok-react/tree/feature/v1/playground)

**Comment by serrg** [comment]
Sorry it was a misclick ;)

**Comment by serrg** [comment]
Additionally I have checked the example with [gettings-started/nextjs](https://github.com/storyblok/getting-started/tree/master/nextjs) and it is working good with the latest version `1.1.6` so it looks like from version `1.1.2` there is some issue with pure React apps.

**Comment by fgiuliani** [comment]
Thank you for taking the time to test @serrg! We'll be taking a look to see what can be causing this issue.

**Comment by fgiuliani** [comment]
Hey @serrg thanks again for testing the SDK and sharing your feedback. I created a PR to fix the issue with the bridge not being initialized for React projects:
https://github.com/storyblok/storyblok-react/pull/223

Could you try updating to the latest version of the SDK?

**Comment by serrg** [comment]
Hi @fgiuliani I have updated package to the latest version (`1.2.1`) and now it works excellent, I confirm that PR fixed the issue 🚀
