### ISSUE TITLE
Nextjs + React + typescript -> Error on Save in editor

### ISSUE THREAD

**Issue by marekrozmus** [storyblok/storyblok-react#229]
Hello :) 

I am trying to use NextJS + Typescript + React.
When I press `Save` or `Publish` on the story in editor:
* On first save this error just flashes and the content is reloaded
* on next save it stays open:
![brave_EhsIcLNwxm](https://user-images.githubusercontent.com/26272040/189327749-61b5a338-66dc-47e5-b22d-40555508fb4a.png)

Am I doing something wrong? It is a simple setup from [tutorial](https://www.storyblok.com/tp/add-a-headless-cms-to-next-js-in-5-minutes) and the only difference is that I have created a NextJS Typescript project.

**Comment by fgiuliani** [comment]
Hey @marekrozmus can you share the code of your project, and show how your content is structured in Storyblok?

**Comment by marekrozmus** [comment]
Hi @fgiuliani :)
Nothing fancy here: https://github.com/marekrozmus/storyblok-ts
And the setup in storyblok is simple page with components from tutorials. Most of the code (if not all ;)) is also from tutorials.

![Zn3C1aae77](https://user-images.githubusercontent.com/26272040/189367865-2bf67e60-095b-496f-91e5-db4d80496361.png)

![brave_cJ64Q28JUO](https://user-images.githubusercontent.com/26272040/189368266-30d3f3da-8056-4d6a-a709-eb226990f619.png)

**Comment by fgiuliani** [comment]
@marekrozmus were you able to identify which line is giving you the error?
Is this happening to you every time you save or publish any page? Because you have an `index.tsx` and a `[...slug].tsx` pages. Or is it happening sometimes?

Did you try re-installing your NPM packages?

I'm not seeing anything wrong 🤔

**Comment by fgiuliani** [comment]
One more thing.
If you see in this line:
https://github.com/marekrozmus/storyblok-ts/blob/main/pages/%5B...slug%5D.tsx#L49

The links the project is checking are the ones that have been already published, at least once. Are your stories in Storyblok published?

**Comment by marekrozmus** [comment]
Yes, all is published - I got error for both index page and others. I have even tried to remove the `[...slug].tsx` but still same issue.
I have checked same code with JS and same space and everything was OK.
I have reinstalled dependencies, updated to latest and still same issue :(

**Comment by marekrozmus** [comment]
It looks like for the Nextjs + JS also doesn't work - same error. 
Whenever I use `story = useStoryblokState(story);`
Not sure what the problem could be - tested in Brave, Chrome and Edge (although they all have the same base).

**Comment by marekrozmus** [comment]
It looks like the `story` comes in the `event` only for `input` action. For the `change` and `published` it is `undefined`.

![brave_tqU7VRnhGX](https://user-images.githubusercontent.com/26272040/189434095-50ab9a9f-ff2f-44d3-b646-5f933af1e042.png)

![brave_rFAndr1NBi](https://user-images.githubusercontent.com/26272040/189434013-048a1b11-4711-4054-94cb-a23dad4bccf7.png)

![brave_kyYQ79jJV2](https://user-images.githubusercontent.com/26272040/189434119-254b8d7c-ff62-47a9-b467-ec2eac897cca.png)

**Comment by fgiuliani** [comment]
Hey @marekrozmus let me contact the Storyblok product team to see if someone else experienced this same issue, or if they know what the reason could be

**Comment by ImSuperlative** [comment]
I think this error may be related to this commit https://github.com/storyblok/storyblok-js/commit/5df12d46b7e47242b167c338d0573bb241ba5ed9#diff-d5a4b3a0309f2337144861084c1014523cced561eb722cb9684c63f5e41e0567L43

**Comment by mweterings** [comment]
Same error here, seems to be happening from version 1.1.5 and up.

**Comment by alexjoverm** [comment]
Hey @marekrozmus and all! Great work on spotting this issue. Indeed it was related to the fact that `input` event has a different data structure to the `change` and `published`.

It's been fixed on this PR so as long as it's merged and a new version of this lib released, should be fixed ;) 

Thanks for making our SDKs better!

**Comment by marekrozmus** [comment]
@alexjoverm Thanks :) So in that case please close my PR https://github.com/storyblok/storyblok-js/pull/136
When the release is usually made? Just wondering if I should wait or make my own forks and packages until the release comes out :)

**Comment by fgiuliani** [comment]
@marekrozmus the new version was just released! Could you try if it's working for you now?

**Comment by marekrozmus** [comment]
@fgiuliani Thank you :) It works now - no more errors 🚀

**Comment by fgiuliani** [comment]
That's good to know @marekrozmus 🙌
Closing the issue
