### ISSUE TITLE
Preview not working with React

### ISSUE THREAD

**Issue by linde12** [storyblok/storyblok-react#27]
Setup:

```ts
storyblokInit({
  accessToken: "NADrWeUETEewAVriVLWwqQtt",
  bridge: true,
  use: [apiPlugin]
});
```

in component:

```ts
const Home = () => {
  const story = useStoryblok('home', { version: 'draft' })
  return <pre>{JSON.stringify(story, null, 4)}</pre>
}
```

This causes the entire page to reload when anything is changed because of the bridge code:

```ts
const useStoryblokBridge = (id, cb, options = {}) => {
  if (typeof window === "undefined") {
    return;
  }
  if (typeof window.storyblokRegisterEvent === "undefined") {
    console.error("Storyblok Bridge is disabled. Please enable it to use it. Read https://github.com/storyblok/storyblok-js");
    return;
  }
  window.storyblokRegisterEvent(() => {
    const sbBridge = new window.StoryblokBridge(options);
    sbBridge.on(["input", "published", "change"], (event) => {
      if (event.action == "input" && event.story.id === id) {
        cb(event.story);
      } else {
        window.location.reload();
      }
    });
  });
};
```

`sbBridge.on(...)` callback always does `window.location.reload()` because initially `event.story.id` will be undefined (it hasn't been fetched yet)

Note: im using create-react-app (no SSR/SSG with e.g. Next.js)

**Comment by fgiuliani** [comment]
Hey @linde12 thanks for your message and feedback.

The issue is already solved in the new version of the SDK:
https://github.com/storyblok/storyblok-react/releases/tag/v1.0.3

Could you double-check if it is working for you now?

**Comment by linde12** [comment]
@fgiuliani It works as expected now, thank you!
