### ISSUE TITLE
Can't get the Visual Editor to work

### ISSUE THREAD

**Issue by Maison-Elan** [storyblok/storyblok-react#310]
I'm in the middle of upgrading my project to the `@storyblok/react` package, coming from the now deprecated `storyblok-react` package. I've successfully upgraded the datafetching to `getStoryblokApi` / `useStoryblokApi` (by the way, what's the difference?). Components were moved from the `DynamicComponent` component to `_app.js`. 

``` js
storyblokInit({
  accessToken: "your-preview-token",
  use: [apiPlugin],
  components,
});
```

This all works correctly.

However, I can't get the Visual Editor to work. 

With the old package I could load the bridge like this:

- Layout.js:

``` js
import Head from '../components/Head'
import Navigation from '../components/Navigation'
import Footer from '../components/Footer'
import StoryblokService from '../utils/storyblok-service'

const Layout = ({ children }) => (
  <div className="bg-gray-300">
    <Head />
    <Navigation />
    {children}
    <Footer />
    {StoryblokService.bridge()}
  </div>
)

export default Layout
```

And then add  the `<SbEditable content={blok} key={blok._uid}>` components wrapped around each of my page builder components. This worked perfectly.

With the new package I'm trying to load the bridge like this:

- Page.js:

``` js
import { useStoryblokState } from "@storyblok/react";

const Page = ({
  story: initialStory,
}) => {

const story = useStoryblokState(initialStory);
...
```

(Note: datafetching does not occur inside this Page component but in an `index.js` file that passes props to the `Page` component).

And in my page builder components I use `import SbEditable from "storyblok-react";'` and `{...storyblokEditable(blok)}` on the top element. Example:

``` js
import SbEditable from "storyblok-react";

const ShortParagraph = ({ blok, language }) => {
  return (
    <div
      className="w-full relative bg-white flex flex-row justify-center"
      {...storyblokEditable(blok)}
....
    >
```

When I open a Story in Storyblok (v2) and click on the `ShortParagraph` component, nothing happens.

## Expected Behavior

The Visual Editor loads correctly. My components are clickable inside the Storyblok editor. Both in V1 and in V2.

## Current Behavior

Clicks on components inside the editor don't interact with the Visual Editor (nothing happens).

## Steps to Reproduce

See code examples.

**Comment by fgiuliani** [comment]
Hey @Maison-Elan! Thanks for your message.

First: `getStoryblokApi` and `useStoryblokApi` are the same. We offer both options since they are coming from a generic JS SDK we have, and `useStoryblokApi` doesn't sound correct for React projects since it's not a Hook.

On the other hand, I see you are importing `SbEditable from "storyblok-react"`, instead of `storyblokEditable from "@storyblok/react"`. Can you check you are importing and using the correct function?

**Comment by Maison-Elan** [comment]
Hey @fgiuliani! Thanks for responding.

Sorry, I copy-pasted the wrong code. It should indeed say `import SbEditable from "@storyblok/react";`:

```js
import SbEditable from "@storyblok/react";

const ShortParagraph = ({ blok, language }) => {
  return (
    <div
      className="w-full relative bg-white flex flex-row justify-center"
      {...storyblokEditable(blok)}
....
    >
```

Regardless, that was not the issue. I managed to get the Visual Editor to work by replacing `useStoryblokState` by `useStoryblok`. Like so:

- Page.js

```js
import { useStoryblok } from "@storyblok/react";

const Page = ({
  story: initialStory,
}) => {

  const story = useStoryblok(initialStory.slug, {
    version: "draft",
    language: language,
    resolve_relations: "featuredPosts.posts",
    resolve_links: "url",
  });

  if (!story?.content) {
    return null;
  }
...
```

Still, my questions are:

- What is the use case for `useStoryblokState` and what is the use case for `useStoryblok`? In other words, what does `useStoryblokState`do that `useStoryblok` does not do? In which scenario should we use `useStoryblokState` and in which scenario should we use `useStoryblok`?
- How can I conditionally call `useStoryblok` when I'm inside the editor (app.storyblok.com)? There's no need to call it outside the editor. Therefore, I would like to skip it when I am outside the editor.

**Comment by fgiuliani** [comment]
hey @Maison-Elan thanks for the updates, and glad to know that it's working for you. You can read more about the hooks in the README file of this repository:

https://github.com/storyblok/storyblok-react#2-listen-to-storyblok-visual-editor-events

But basically:
- `useStoryblok` gets the slug of the story, gets the data from Storyblok API, and initializes the bridge connection. `useStoryblokState` should work the same, but already receiving a story instance (not calling the API to get the content).
- For `useStoryblokState` we have a preview parameter. If it's set to `false`, the bridge is not initialized. We may need to add the same parameter to `useStoryblok` hook 🤔

**Comment by fgiuliani** [comment]
@Maison-Elan are you using the latest version of the lib? That sounds strange, it's working properly for me 🤔

**Comment by Maison-Elan** [comment]
@fgiuliani Yep,  `"@storyblok/react": "^1.3.3",`

**Comment by Maison-Elan** [comment]
Also, I'm using Next.js:

- `"next": "^13.0.0",`
- `"react": "^18.2.0",`
- `"react-dom": "^18.2.0",`

**Comment by Maison-Elan** [comment]
@fgiuliani I've managed isolate the issue somewhat. It turns out `useStoryblokState` does work, but only after a keystroke inside the form (on the right-hand side of the editor). When I open a Story and click on any blok, the clicks don't register (nothing happens) until I press down on a key (letters, numbers, etc.) inside a field in the form of a component. After that initial keystroke, the Visual Editor works as expected.

I also noticed that when the Story loads inside the Visual Editor the data attributes `data-blok-c` and `data-blok-uid` are not set on the editable elements. However, as soon as I enter something inside field, these attributes are set. When I use `useStoryblok` I don't have this problem because `data-blok-c` and `data-blok-uid` are set when the Story loads inside the editor.

Any idea why this is happening?

**Comment by guanacone** [comment]
Facing similar issue as @Maison-Elan. In the visual editor, when editing the content of an alternate language, the content of the corresponding language is only displayed when I start edditing a field. In other words, when I switch from english to german, the german content gets displayed only when I start typing in a field.

**Comment by arorachakit** [comment]
Hey @Maison-Elan and @guanacone ! 
This looks a bit strange, generally, the visual editor along with live editing works right away. It would be really helpful if you could share your code with us so we can take a look and find something if there is any :) 

Also, I would like to share our Ultimate Tutorial Series - https://www.storyblok.com/tp/nextjs-headless-cms-ultimate-tutorial
The [1st part](https://www.storyblok.com/tp/add-a-headless-cms-to-next-js-in-5-minutes) here takes you to the easiest approach to how you can make set it up. I think if you're following a similar approach it should work fine. 
@guanacone It can be helpful for you to take a look here as well at the [6th part](https://www.storyblok.com/tp/manage-multilingual-content-in-storyblok-and-next-js), which shows the internationalization part. You can follow the complete series of tutorials as well if you want to see other functionalities. :)

**Comment by Maison-Elan** [comment]
Hey @arorachakit!

Sure, I can share some code. What do you need? Other than what I have already shared.

I have set Storyblok up like it is described in your tutorial. Also, I'm using Field level translations instead of Folder level translations and have the **Translatable slugs** and **Advanced paths** apps installed. This works like this:

- There's a `blog` folder (just like in your tutorial).
- Inside this folder is where all the blog posts are created and published.
- The default language is English.
- The real path template on the blog folder is setup like this: `{{if(options.lang == '')}}en/blog/{{#else}}{{lang}}/blog/{{/if}}`

In the old setup (`{StoryblokService.bridge()}`) with `<SbEditable content={blok} key={blok._uid}>` I did not have any issues with the Visual Editor. It worked immediately after opening a Story (e.g. a Blog post) in Storyblok.

**Comment by arorachakit** [comment]
Hey @Maison-Elan ! 
If the setup is the same as our tutorial then I think it should work. Because even if you try to clone [that project](https://github.com/storyblok/next.js-ultimate-tutorial/tree/part-6) - you will see it works. I don't think the setup inside Storyblok is an issue. It could be something in the code related to initialization. 

If you can share some code, that shows the complete setup of yours that would be great. If you cannot share the complete  repo, maybe you can share a temp project that just shows the setup?

**Comment by Maison-Elan** [comment]
Hey @arorachakit,

Ok, will share the Homepage route:

- _app.js

```js
import Teaser from "../components/pagebuilder/Teaser";
import Feature from "../components/pagebuilder/Feature";
import FeaturedPosts from "../components/pagebuilder/FeaturedPosts";
import Grid from "../components/pagebuilder/Grid";
import ImageSlider from "../components/pagebuilder/ImageSlider";
import LongParagraph from "../components/pagebuilder/LongParagraph";
import ShortParagraph from "../components/pagebuilder/ShortParagraph";

const components = {
  teaser: Teaser,
  grid: Grid,
  feature: Feature,
  featuredPosts: FeaturedPosts,
  imageSlider: ImageSlider,
  shortParagraph: ShortParagraph,
  longParagraph: LongParagraph,
};

storyblokInit({
  accessToken: process.env.NEXT_PUBLIC_SB_API_PREVIEW_KEY,
  use: [apiPlugin],
  components,
});

....
```

- index.js

```js
import Page from "../components/contenttypes/Page";
import Layout from "../components/Layout";
import { getStoryblokApi, useStoryblokState } from "@storyblok/react";

function Homepage(props) {
  const { story: initialStory, header, footer, language } = props;

  // Enables the Visual Editor (Storyblok Bridge V2)
  // First argument must be the story object (required), second must be the bridgeOptions (optional)
  const story = useStoryblokState(initialStory, {
    language: language,
    resolve_relations: "featuredPosts.posts",
  });

  if (!story.content) {
    return null;
  }

  return (
      <Layout language={language} header={header} footer={footer}>
        <Page
          story={story}
          id={story.id}
          language={language}
        />
      </Layout>
  );
}

export async function getServerSideProps({ query }) {
  const storyblokApi = getStoryblokApi();
  const language = query.language || "en";
  const page = await storyblokApi.get(`cdn/stories/home`, {
    language: language,
    resolve_relations: "featuredPosts.posts",
    resolve_links: "url",
  });

  const footer = await storyblokApi.get(`cdn/stories/blocks/footer`, {
    language: language,
    resolve_links: "url",
  });

  const header = await storyblokApi.get(`cdn/stories/blocks/header`, {
    language: language,
    resolve_links: "url",
  });

  return {
    props: {
      story: page.data ? page.data.story : false,
      footer: footer.data.story,
      header: header.data.story,
      language,
    },
  };
}

export default Homepage;
```

- Page.js

```js
import { StoryblokComponent } from "@storyblok/react";
import { useEffect } from "react";

const Page = ({
  story,
  id,
  language,
}) => {

  return (
    <>
      <main>
        {story.content.body?.map((blok, index) => (
          <StoryblokComponent
            blok={blok}
            storyId={id}
            key={blok._uid}
            language={language}
            sortOrder={index}
          />
        ))}
      </main>
    </>
  );
};

export default Page;
```

- ShortParagraph.js (blok)

```js
import { render } from "storyblok-rich-text-react-renderer";
import { storyblokEditable } from "@storyblok/react";

const ShortParagraph = ({ blok }) => {
  return (
    <div className="md:w-2/3 w-full text-left" {...storyblokEditable(blok)}>
      <div>
        <h2 className="leading-intro-header p-0 m-0 font-normal text-primary-black md:text-paragraph-header text-3xl">
          {blok.title}
        </h2>
      </div>
      <div className="mt-6 leading-8 paragraph-container text-secondary-gray text-lg font-normal font-cerebri antialiased">
        {render(blok.text)}
      </div>
    </div>
  );
};

export default ShortParagraph;
```

**Comment by guanacone** [comment]
- _app.tsx
```js
...

storyblokInit({
  accessToken: process.env.NEXT_PUBLIC_STORYBLOK_PREVIEW_TOKEN,
  use: [apiPlugin],
  components: {
    'feature-grid': FeatureGrid,
    'home-hero-stage': HomeHeroStage,
    'testimonial-grid': TestimonialGrid,
    'cta-with-image': CtaWithImage,
    faqs: FAQs,
    'course-grid': CourseGrid,
    'featured-blog-posts': FeaturedBlogPosts
  }
});

...
```
- index.tsx
```js
...

const Home = ({
  labels,
  story,
  layout,
  locale,
  locales,
  preview
}: InferProps<typeof getStaticProps>) => {
  const sbStory = useStoryblokState(
    story,
    {
      language: locale
    },
    preview
  );

  const featureGrid = sbStory.content?.body.find(
    (element: IFeatureGridBlok) => element.component === 'feature-grid'
  );
  const homeHeroStage = sbStory.content?.body.find(
    (element: IHomeHeroStageBlok) => element.component === 'home-hero-stage'
  );
  const testimonialGrid = sbStory.content?.body.find(
    (element: ITestimonialGridBlok) => element.component === 'testimonial-grid'
  );
  const ctaWithImage = sbStory.content?.body.find(
    (element: ICtaWithImageBlok) => element.component === 'cta-with-image'
  );
  const faqs = sbStory.content?.body.find(
    (element: IFaqBlok) => element.component === 'faqs'
  );
  const courseGrid = sbStory.content?.body.find(
    (element: ICourseGridBlok) => element.component === 'course-grid'
  );
  const featuredBlogPosts = sbStory.content?.body.find(
    (element: IFeaturedBlogPosts) => element.component === 'featured-blog-posts'
  );
  return (
    <>
      <GlobalContextProvider labels={labels} {...storyblokEditable(sbStory)}>
        <DefaultLayout
          locale={locale}
          locales={locales}
          SEO={sbStory.content?.SEO}
          canonical={sbStory.content?.canonical_URL}
          no_index={sbStory.content?.no_index}
          defaultFullSlug={sbStory.default_full_slug}
          translatedSlugs={sbStory.translated_slugs}
          data={layout}
        >
          {homeHeroStage && <HomeHeroStage blok={homeHeroStage} />}
          {featureGrid && <FeatureGrid blok={featureGrid} />}
          {courseGrid && <CourseGrid blok={courseGrid} />}
          {testimonialGrid && <TestimonialGrid blok={testimonialGrid} />}
          {ctaWithImage && <CtaWithImage blok={ctaWithImage} />}
          {faqs && <FAQs blok={faqs} />}
          {featuredBlogPosts && (
            <div className="bg-gray-50 py-20">
              <div className="max-w-7xl mx-auto">
                <FeaturedBlogPosts blok={featuredBlogPosts} />
              </div>
            </div>
          )}
        </DefaultLayout>
      </GlobalContextProvider>
    </>
  );
};

...
```
- quick demo of my multilanguage issue
https://www.loom.com/share/120f8c0728144a5688b317b2c632d22c

**Comment by arorachakit** [comment]
Hey @Maison-Elan and @guanacone! How are you both?
Thank you for sharing the code and recording, all of it really helped us find the issues. 

@Maison-Elan - You're fetching the published data which doesn't include the  `_editable` key inside the components. This key helps the bridge to identify the components and make them clickable. If you add a parameter `version: draft` while you're fetching the data with `storyblokApi`, you will be able to see the bridge working fine. And this is how we recommend you use it this way as well, it won't make much sense to edit the published content. You can always edit the draft content inside the Visual Editor and then publish it to retrieve on your production env. 
Also, you can take a look at this - https://www.storyblok.com/docs/Guides/storyblok-latest-js which contains the editable part I mentioned.

@guanacone - The video really helped here. The issue here is related to the real path, which seems to be set for your home story. Now when you set a real path, the visual editor's location remains the same even when you switch the language. And if the URL remains the same, it shows the data for your default locale. If you try on any of the stories where you don't have a real path set, it should work as you expect. If you want your home story to change the path if you change the language and still be "/" and "locale/" where you don't have the slug included - I'd recommend you use the Advanced Paths app we have - https://www.storyblok.com/apps/advanced-paths You can set programmable paths with this app, but you need to set those for all stories then.   

I hope this was helpful, let me know if you need anything else :)

**Comment by Maison-Elan** [comment]
@arorachakit Thanks a lot for looking into this! I can confirm that this does indeed fix my problem. By adding `version: draft` as a parameter to the `storyblokApi.get` call, the editor loads as expected. Each component is immediately clickable.

For others reading this, here's an example:

```js
export async function getServerSideProps({ query }) {
  const storyblokApi = getStoryblokApi();
  const language = query.language || "en";
  const page = await storyblokApi.get(`cdn/stories/home`, {
    language: language,
    resolve_relations: "featuredPosts.posts",
    resolve_links: "url",
    version: "draft", // new parameter that fixed the problem of initialising the Visual Editor with useStoryblokState
  });

```

**Comment by Maison-Elan** [comment]
@arorachakit So, how does this work with Next.js Preview Mode? With `getServerSideProps` I can do something like this to toggle `draft` and `published` version depending on if I'm inside the editor:

```js
export async function getServerSideProps({ query }) {
  const storyblokApi = getStoryblokApi();
  const language = query.language || "en";
  const page = await storyblokApi.get(`cdn/stories/home`, {
    language: language,
    resolve_relations: "featuredPosts.posts",
    resolve_links: "url",
    version: query._storyblok ? "draft" : "published",
  });
...
```

This works fine.

Obviously, this does not work with `getStaticProps` routes since there's no `query` object. What are the steps involved to get this to work with Preview Mode?

**Comment by arorachakit** [comment]
@Maison-Elan Awesome! Good to know that you're able to fix the issue like this. 
There is a similar approach to Preview mode, you get to know if you are in the preview mode or not from the context. And if you're in preview mode, you should fetch the draft version. If not, then published - this would be ideal. 

Here is a link on how to add the preview mode here - https://www.storyblok.com/tp/add-a-headless-cms-to-next-js-in-5-minutes#adding-preview-mode
And if you scroll down here - https://www.storyblok.com/tp/add-a-headless-cms-to-next-js-in-5-minutes#loading-the-draft-version-only-in-preview-mode you will see how we use this context. 

Here is a link to one of my code repos - https://github.com/arorachakit/cityjs-singapore/blob/master/pages/%5B...slug%5D.js#L33 
In this line, you can see the way I am using preview here. This same can be used to change the versions :)

**Comment by Maison-Elan** [comment]
@arorachakit Great, that works!

So, for others reading this:

1. I created a separate access token in Storyblok for Next.js Preview Mode and added it to `preview.js`:

```js
export default async function preview(req, res) {
  const { slug = "" } = req.query;
  // get the storyblok params for the bridge to work
  const params = req.url.split("?");

  // Check the secret and next parameters
  // This secret should only be known to this API route and the CMS
  if (req.query.secret !== process.env.SB_API_PREVIEW_MODE_KEY) {
    return res.status(401).json({ message: "Invalid token" });
  }

  // Enable Preview Mode by setting the cookies
  res.setPreviewData({});

  // Set cookie to None, so it can be read in the Storyblok iframe
  const cookies = res.getHeader("Set-Cookie");
  res.setHeader(
    "Set-Cookie",
    cookies.map((cookie) =>
      cookie.replace("SameSite=Lax", "SameSite=None;Secure")
    )
  );

  // Redirect to the path from entry
  res.redirect(`/${slug}?${params[1]}`);
}
```

- `exit-preview.js`:

```js
export default async function exit(req, res) {
  const { slug = "" } = req.query;
  // Exit the current user from "Preview Mode". This function accepts no args.
  res.clearPreviewData();

  // set the cookies to None
  const cookies = res.getHeader("Set-Cookie");
  res.setHeader(
    "Set-Cookie",
    cookies.map((cookie) =>
      cookie.replace("SameSite=Lax", "SameSite=None;Secure")
    )
  );

  // Redirect the user back to the index page.
  res.redirect(`/${slug}`);
}
```

2. Then, I added two preview URLs in Storyblok:

Preview Mode URL: 

`https://localhost:3010/api/preview?secret=SECRET_TOKEN&slug=` (with the token from step 1)

Exit Preview Mode URL: 

`https://localhost:3010/api/exit-preview?slug=`

3. Finally, I modified `useStoryblokState` by adding the preview parameter inside a route that uses `getStaticProps`:

- `[slug].js`:

```js
function Post(props) {
  const {
    story: initialStory,
    preview,
  } = props;

  // Enables the Visual Editor (Storyblok Bridge V2)
  // First argument must be the slug (required), second must be the apiOptions (StoriesParams) (required), third the brideOptions (optional argument to customize bridge behaviour)

  const story = useStoryblokState(
    initialStory,
    {
      language: language,
    },
    preview
  );
...

export async function getStaticProps({ params, preview }) {
  const storyblokApi = getStoryblokApi();
  let language = params.language;
  // Get blog posts
  const post = await storyblokApi.get(`cdn/stories`, {
    language: language,
    starts_with: `blog/${params.slug}`,
    resolve_links: "url",
    version: preview ? "draft" : "published",
  });
```

**Comment by guanacone** [comment]
@arorachakit thanks for the explainations, it indeed works with stories that don't have a `realPath` set and the work arround with the `Advanced Paths APP` works as well.

> You can set programmable paths with this app, but you need to set those for all stories then

Setting a programmable path for all stories is not an option in our case as the editors are able to create new stories and don't have the knowlege to do so. The only story where we set a `realPath` is for the top domain. What is the recommended way to setup a story for the top level? So far we where using `home` or `index` as slug and setting a `realPath` of `/`, but as you mentioned:

> when you set a real path, the visual editor's location remains the same even when you switch the language. And if the URL remains the same, it shows the data for your default locale

Thank you for clarification.

**Comment by arorachakit** [comment]
Awesome @Maison-Elan !! 

@guanacone If you don't want to use the app, and just want it on one story - maybe you can keep it the way it usually is, without realPath. Your content editors can also edit the story which has the slug index/home (so this will make the visual editor work perfectly), but when you're on production you can just change the slug there. I mean you can avoid using the real path and retrieve the data manually for that story. This depends on the implementation mostly, but for example - when in getStaticPaths you can include this route ('/') manually, and when in getStaticProps you can fetch home/index stories data for this path. You can even make it such a way that it only happens in production, and in dev it stays as home/index. Again, it completely depends on your approach, but this can be one of many approaches. 
You can always control most of the things from the front end as it stays with you. In our default demo (which you can create as well, from adding a new space), you will see that we even allow the content editors to change the header/footer and the complete layout in a story named config. They can see the changes as well happening in real-time as the story is configured that way, but we just use that story to store the data and fetch the data during the app bootup to make the layout out of that. This is just an example to show the possibilities we have, and the number of different solutions we can take to make it work. 
I hope it was helpful.


Also, @Maison-Elan and @guanacone - since now we know that the sdk and visual editor work as expected, I think we can close this issue. Please let us know if you have any questions in the future as well :) 
You can also join our [discord](https://discord.com/invite/WmMYYQp), the community is very active and you can even find answers to many questions there as well as many interesting topics.

**Comment by guanacone** [comment]
Thanks for the support!
