### ISSUE TITLE
StoryblokComponent `forwardRef` to a "real" component

### ISSUE THREAD

**Issue by biirus** [storyblok/storyblok-react#337]
[storyblokurl]: https://www.storyblok.com?utm_source=github.com&utm_medium=issue-template

Hey guys!
Thank you for providing a nice package that simplifies the work a lot.

Here is the thing though, I have a component which uses a `StoryblokComponent` as its child and it tries to pass a `ref` to it. However, the `StoryblokComponent` implementation does not allow me do to so. And thus I've got an error

```
Function components cannot be given refs. Attempts to access this ref will fail. Did you mean to use React.forwardRef()?
```

Here is my usecase:

```javascript
<Intersection onObserve={handleComponentObserve}>
    <StoryblokComponent blok={blok} key={blok._uid} />
</Intersection>
```

Whereas `Intersection` component modifies its children and adds a ref to the first of them:

```javascript
const wrapperRef = useRef(null)
const withRef = useMemo(() => {
    const [child] = Children.toArray(props.children)
    return isSingleReactComponent(child)
      ? cloneElement(child, { ref: wrapperRef })
      : child
}, [props.children])
```

Since in my case the first child is `StoryblokComponent` then `Intersection` tries to add a `ref` to it.

## Expected Behavior  

`StoryblokComponent` passes a `ref` down to a "real" component.

## Current Behavior

Got an error:
```
Function components cannot be given refs. Attempts to access this ref will fail. Did you mean to use React.forwardRef()?
```

## Steps to Reproduce

1. Create a component
2. Create a ref inside of it
3. Use `StoryblokComponent` as a child
4. Pass a ref (created on step 2) to it
5. Check the console, the error will be listed there

**Comment by fgiuliani** [comment]
Hey @biirus thank you very much for raising this issue, and creating a PR that solves it! Really appreciate your contribution.

We are about to merge a PR that will introduce some breaking changes and generate a new major version of the SDK. After we do it, we will take a look at your PR and evaluate the possibility of merging it. What do you think?

**Comment by biirus** [comment]
Ah, I see...
Is there any case you can merge the PR first? Cuz it's backward compatible, and maybe it would be even easier then to apply you bigger changes on top of it.

In any case, it's your decision - I'm not aware of technical details you're gonna merge =)

**Comment by fgiuliani** [comment]
Hey @biirus we discussed with the team and we agree with you. PR merged! Thanks again for your contribution 🙏
