### ISSUE TITLE
Remix app - "rendered fewer hooks than expected" when navigating

### ISSUE THREAD

**Issue by TimoWestland** [storyblok/storyblok-react#413]
[storyblokurl]: https://www.storyblok.com?utm_source=github.com&utm_medium=issue-template

I have a remix app with storyblok. Everything works fine so far, however when I try to navigate in the visual editor trough clicking on a link instead of using the Storyblok panel on the left, I get the following react error:

```
Error: Rendered fewer hooks than expected. This may be caused by an accidental early return statement.
    at renderWithHooks (https://localhost:3010/build/_shared/chunk-AZPU6RDF.js:11803:19)
    at updateFunctionComponent (https://localhost:3010/build/_shared/chunk-AZPU6RDF.js:14149:28)
    at beginWork (https://localhost:3010/build/_shared/chunk-AZPU6RDF.js:15455:22)
    at beginWork$1 (https://localhost:3010/build/_shared/chunk-AZPU6RDF.js:19246:22)
    at performUnitOfWork (https://localhost:3010/build/_shared/chunk-AZPU6RDF.js:18694:20)
    at workLoopSync (https://localhost:3010/build/_shared/chunk-AZPU6RDF.js:18630:13)
    at renderRootSync (https://localhost:3010/build/_shared/chunk-AZPU6RDF.js:18609:15)
    at recoverFromConcurrentError (https://localhost:3010/build/_shared/chunk-AZPU6RDF.js:18231:28)
    at performSyncWorkOnRoot (https://localhost:3010/build/_shared/chunk-AZPU6RDF.js:18373:28)
    at flushSyncCallbacks (https://localhost:3010/build/_shared/chunk-AZPU6RDF.js:8774:30)
```

I use the Link component provided by `@remix.run/react`

Perhaps navigating like this is unsupported behaviour but having an error like this on the screen is not very nice for the users.

---

## Expected Behavior

I would expect that the visual editor would load the page related to the link that was clicked.
E.g. home -> About. 

## Current Behavior

Instead I get the react error above which is also quite vague and doesn't give me a clue where less hooks were rendered than expected.

## Steps to Reproduce

1. Click on a link 
2. See the React error on screen

Video for reference (first navigation trough storyblok, which works fine, then clicking a link which doesn't work)

https://user-images.githubusercontent.com/3959082/217540384-1dcee8c8-afda-4eb2-a7da-c2695e718073.mov

**Comment by fgiuliani** [comment]
Hey @TimoWestland thanks for creating this issue.
Do you have any piece of code you can share in order for us to reproduce the issue? I haven't experienced a scenario like this before.

**Comment by TimoWestland** [comment]
Hi @fgiuliani

Thanks for your reply! I'll check if I can share the repo :)

**Comment by TimoWestland** [comment]
Hi @fgiuliani,

Apologies for the delay, but we decided to make the code public so it's easy to share now: https://github.com/saltagency-io/saltagency.io

We did a redesign so it looks different than the original video now. The error is now caught and a error page is rendered, however you can still see the same error "rendered with fewer hooks" in the dev tools console when navigating in storyblok.

**Comment by TimoWestland** [comment]
Only thing that I can find in the code of this package is this line https://github.com/storyblok/storyblok-react/blob/main/lib/index.ts#L39 where there is a early return before a `useEffect`, which is generally what causes React to throw this error.

**Comment by fgiuliani** [comment]
Hi @TimoWestland! Thanks for sharing the code.

The `useStoryblokState` hook should be called once per page/route.

I see that the `useStoryblokState` hook is being used in the `root.jsx` file:
https://github.com/saltagency-io/saltagency.io/blob/63cb4e76808403e40af7c324d241a66b49a01248/app/root.tsx#L142

And it's also being called on each one of the roots:
https://github.com/saltagency-io/saltagency.io/blob/63cb4e76808403e40af7c324d241a66b49a01248/app/routes/%24slug.tsx#L78

https://github.com/saltagency-io/saltagency.io/blob/63cb4e76808403e40af7c324d241a66b49a01248/app/routes/careers/%24slug/index.tsx#L76

https://github.com/saltagency-io/saltagency.io/blob/63cb4e76808403e40af7c324d241a66b49a01248/app/routes/contact.tsx#L132

As Remix works with nested routes, it may be calling the hook twice per page. 
Is there any reason why you need to call it on the `root.jsx` file?

**Comment by TimoWestland** [comment]
Hi @fgiuliani,

Thanks for your quick response! Much appreciated.

However removing `useStoryblokState` from `root.tsx` doesn't solve the issue unfortunately. I've made an branch with the change here: https://github.com/saltagency-io/saltagency.io/tree/storyblok-fix-attempt

The error still persists:
<img width="841" alt="image" src="https://user-images.githubusercontent.com/3959082/222695947-2c0956f9-08b4-4678-bf4c-374bc9f49898.png">

I'm not 100% sure why I've added `useStoryblokState` to `root.tsx`, but I expect it's because I want to have the shared/global story that has the header and the footer. I think the `useStoryblokState` hook is to setup the bridge so the live preview will work for the bloks of this story? (new to storyblok so not sure haha)
I see the live preview is not working for the header and the footer currently so my current solution doesn't work.

I think I used this guide as a reference to set this up: https://www.storyblok.com/tp/create-dynamic-menus-in-storyblok-and-nuxt

Open to suggestions to have a better way to fetch the header and footer from the root and render it there.

**Comment by TimoWestland** [comment]
Allright @fgiuliani  your answer did point me in the right direction to find the solution.

I needed to remove the `useStoryblokState` from `root.tsx` indeed, but the issue was also caused by me not properly implementing a component for `layout` and instead rendering the navigation and footer directly inside of `root.tsx`.

I've made some changes to properly implement this: https://github.com/saltagency-io/saltagency.io/pull/3/files

If I can make a suggestion I think it would be great if there would be some examples of a better way to implement a global layout with a header/footer with storyblok in a remix.app that utilizes the nested routing provided by remix. It would be a shame to not use this and having to add `<Layout></Layout>` component in every file inside the `/routes` folder instead. 

I think having to have a content type for layout that als results in `/layout` being a valid route inside storyblok is a bit strange in the first place. It results in me having to catch this route here: https://github.com/saltagency-io/saltagency.io/pull/3/files#diff-7313e60cdb920efd35b7d38aff015ddc434f21fa3c2ecf5c56e8b68d22f89979R35
So that users will never see it.

Also when viewing the `/layout` story inside storyblok the page will now end up like this:
<img width="1756" alt="image" src="https://user-images.githubusercontent.com/3959082/222739106-d181a61e-338c-4f13-98e6-aa388d68d5e3.png">

I can live with that for now but I'm pretty sure there is a better way to solve this, but I haven't found any documentation on that so far.

Thanks for your help again! At least the navigation issue is resolved now.

Feel free to close this issue.

**Comment by fgiuliani** [comment]
Hi @TimoWestland! It's great to hear that the issue is not happening anymore for you!

About the suggestion of creating docs on how to implement a global layout on Remix projects, that sounds like a great idea. I'll share that with the team and will try to work on that as soon as possible!
Ideally, we want to create a "Remix Ultimate Tutorial", like the ones we have for Next.js, Nuxt, and other technologies. We'll be working on that soon.

Again, thanks for the suggestions and glad to hear the issue is not happening anymore.
