### ISSUE TITLE
Missing loading state when fetching a story with useStoryblok hook

### ISSUE THREAD

**Issue by oliverstreissi** [storyblok/storyblok-react#432]
[storyblokurl]: https://www.storyblok.com?utm_source=github.com&utm_medium=issue-template

When fetching a story with the useStoryblok hook in React, I'm not able to tell if the request is still in progress or if it failed, because in both cases an empty object is returned.

---

## Expected Behavior

Return an isLoading state when fetching a story with the useStoryblok hook. This would make it easier to render a loading screen, when isLoading is true and a 404 page when the request failed.

## Current Behavior

At the moment the hook returns an empty object initially and when the request has failed.

## Steps to Reproduce

1. Create a new react app and initialize with Storyblok
2. Add the following code to App.tsx:

```
function App() {
  const slug = pathname === '/' ? 'home' : pathname(replace('/', '');

  const story = useStoryblok(slug, { version: "draft" });

  if (!story?.content) return <div>Loading ...</ div>

  return (
    <StoryblokComponent blok={story.content} />
  )

}
```

And that is what I would want to achiev:
```
function App() {
  const slug = pathname === '/' ? 'home' : pathname(replace('/', '');

  const { story, isLoading } = useStoryblok(slug, { version: "draft" });

  if (!story?.content && isLoading) return <div>Loading ...</ div>

  if (!story?.content) return <div>404 not found </ div>

  return (
    <StoryblokComponent blok={story.content} />
  )

}
```

If this is also achievable with the current implementation of the hook, please enlighten me!

**Comment by fgiuliani** [comment]
Hey @oliverstreissi thanks for sharing the suggestion. We will discuss the idea with the team and will come back to you

**Comment by fgiuliani** [comment]
Tagging @alexjoverm for visibility

**Comment by andreehultgren** [comment]
@oliverstreissi
This custom behavior is achievable with something like this:

```JavaScript
import React, { useState, useEffect } from "react"
import { storyblokInit, apiPlugin, StoryblokComponent } from "@storyblok/react";

const { storyblokApi } = storyblokInit({
  accessToken: "YOUR_ACCESS_TOKEN",
  use: [apiPlugin],
});

function MyComponent({slug}){
    const [loading, setLoading] = useState(false);
    const [data, setData] = useState(null);
    useEffect(()=>{
        setLoading(true);
        storyblokApi.get(slug, { version: "draft" }).then((response)=>{
            setLoading(false);
            setData(response.data)
        }).catch({
            setLoading(false);
            setData(null)
        });
    }, [slug])

    if(loading){
        return <p>Loading</p>
    }
    if(!!!data){
        return <p>404</p>
    }
    // Depends on data returned
    return <StoryblokComponent blok={data} />

}


```

**Comment by oliverstreissi** [comment]
@fgiuliani yes with the update it's working, thanks!
