### ISSUE TITLE
How to use with remix

### ISSUE THREAD

**Issue by anakinsolo** [storyblok/storyblok-react#446]
[storyblokurl]: https://www.storyblok.com?utm_source=github.com&utm_medium=issue-template

I am having hardtime getting this to work without hardcoding API Token. I understand that this should be use inside app/root.tsx, but given the fact of how remix works, unless you hardcode the token, there's nothing that listed here helps with fetching the token from an .env file. Is there any other places to init the storyblok beside app/root.tsx

---

## Expected Behavior

this should be able to be somewhere than the root, right?
```
storyblokInit({
  accessToken: 'token',
  use: [apiPlugin],
  components: {},
});
```

## Current Behavior

The only place that storyblokInit() could be used in app/root.tsx

## Steps to Reproduce

1. Install remix `npx create-remix@latest`
2. Install storyblok/react package
3. Add storyblokInit() to root.tsx
```
//app/root.tsx
...
import { apiPlugin, storyblokInit } from '@storyblok/react';
import { ComponentList } from './components/ComponentList';

storyblokInit({
  accessToken: process.env.STORYBLOK_TOKEN,
  use: [apiPlugin],
  components: ComponentList,
});
...
//The rest of the root file
const MainStyles = ( {children} :{children: ReactNode}) => {
  return (
    <html lang="en" className="h-full">
      <head>
        <Meta />
        <Links />
      </head>
      <body className="h-full">
        {children}
        <ScrollRestoration />
        <Scripts />
        <LiveReload />
      </body>
    </html>
  );
};

export default function App() {
  return (
    <MainStyles>
      <Navigation />
      <Outlet />
      <Footer />
    </MainStyles>
  );
}

```
4. Make a .env file with STORYBLOK_TOKEN
5. Run the project with `npm i` and `npm run dev`. Go to localhost:3000, open browser console and see process is not defined

**Comment by fgiuliani** [comment]
Hi @anakinsolo thanks for sharing your thoughts.

If you want to use an env variable, you can follow this approach:
https://remix.run/docs/en/1.14.0/guides/envvars#browser-environment-variables

About using `storyblokInit` in a different location, the idea is that function is executed only once for the whole app. That's why we call that function on the `root.jsx` file

**Comment by anakinsolo** [comment]
> Hi @anakinsolo thanks for sharing your thoughts.
> 
> If you want to use an env variable, you can follow this approach: https://remix.run/docs/en/1.14.0/guides/envvars#browser-environment-variables
> 
> About using `storyblokInit` in a different location, the idea is that function is executed only once for the whole app. That's why we call that function on the `root.jsx` file

Hi, thank you for the info. I actually did try the solutions in that link prior to asking in here, none of them worked.

**Comment by fgiuliani** [comment]
Hi @anakinsolo!
I did a test on this repository and it's working correctly for me. Can you check if this approach works for you?
https://github.com/fgiuliani/remix-smashing-workshop

**Comment by anakinsolo** [comment]
> Hi @anakinsolo! I did a test on this repository and it's working correctly for me. Can you check if this approach works for you? https://github.com/fgiuliani/remix-smashing-workshop

Hi @fgiuliani , thank you for your help. It doesn't work
![image](https://user-images.githubusercontent.com/8152024/224631707-e86f9204-0c21-4fb5-8c44-50231ef8667d.png)
 
I changed your token to my token. It's the same error. Yesterday I had to move both the storyblokInit() and the getStoryblokAPI() to the loader and it worked. But that means I can only use it for getting data from the API, and not other rendering features of the module.

**Comment by fgiuliani** [comment]
Hi @anakinsolo. Maybe some debugging is needed, as the error doesn't look related to the code of the repository I shared (there is no loader involved on the root file). And, in the example I shared, it's working correctly 🤔

**Comment by anakinsolo** [comment]
> Hi @anakinsolo. Maybe some debugging is needed, as the error doesn't look related to the code of the repository I shared (there is no loader involved on the root file). And, in the example I shared, it's working correctly 🤔

Hi @fgiuliani, in that repo, the $.jsx has a loader(), which uses storyblokApi to call the get() method. And I think the actual error was thrown here
```
export const useStoryblokApi = (): StoryblokClient => {
  if (!storyblokApiInstance) {
    console.error(
      "You can't use getStoryblokApi if you're not loading apiPlugin."
    );
  }

  return storyblokApiInstance;
};
```
For why `if (!storyblokApiInstance)` is true, I think it fails here
```
export const storyblokInit = (pluginOptions: SbReactSDKOptions = {}) => {
  const { storyblokApi } = sbInit(pluginOptions);
  storyblokApiInstance = storyblokApi;

  componentsMap = pluginOptions.components;
};
```
which was call in the root.jsx 
```
storyblokInit({
  accessToken: process.env.STORYBLOK_API_TOKEN,
  use: [apiPlugin],
  components,
});
```
But here, the process.env.STORYBLOK_API_TOKEN fails to return any token

**Comment by fgiuliani** [comment]
It's pretty strange, as it's working correctly for me 🤔 
Maybe a silly question, but did you rename `.env.example` to `.env`?

**Comment by anakinsolo** [comment]
> It's pretty strange, as it's working correctly for me thinking Maybe a silly question, but did you rename `.env.example` to `.env`?

@fgiuliani , yeah, I am absolutely sure that I did
![Screenshot from 2023-03-14 00-21-12](https://user-images.githubusercontent.com/8152024/224846143-075408eb-78db-4538-a06c-43115383ebf8.png)

**Comment by anakinsolo** [comment]
> It's pretty strange, as it's working correctly for me thinking Maybe a silly question, but did you rename `.env.example` to `.env`?

Hi @fgiuliani , let's say it works in your test. But I noticed that you do not have a server.js file. And in my repo, I have one https://github.com/anakinsolo/storyblok-demo/tree/test-single-page, which is for usage in vercel. Do you think that could be the reason why I had the process not defined in the first place?

**Comment by fgiuliani** [comment]
Hi @anakinsolo. Did you try running the repository I shared with you without changing anything? Is it working?

I don't have a server.js because I didn't deploy this project, I'm running it locally only. Not sure if that's causing the issue 🤔 

One difference I see between your project and the one I shared is that you are calling the storyblokInit function inside a loader:
https://github.com/anakinsolo/storyblok-demo/blob/test-single-page/app/root.tsx#L22

When in my project, it's not:
https://github.com/fgiuliani/remix-smashing-workshop/blob/main/app/root.jsx#L25

**Comment by anakinsolo** [comment]
> Hi @anakinsolo. Did you try running the repository I shared with you without changing anything? Is it working?
> 
> I don't have a server.js because I didn't deploy this project, I'm running it locally only. Not sure if that's causing the issue 🤔
> 
> One difference I see between your project and the one I shared is that you are calling the storyblokInit function inside a loader: https://github.com/anakinsolo/storyblok-demo/blob/test-single-page/app/root.tsx#L22
> 
> When in my project, it's not: https://github.com/fgiuliani/remix-smashing-workshop/blob/main/app/root.jsx#L25

Hi, I tried again your solution, cloned the repo to another computer and it shows on the browser now. But I do not thing that it works correctly, as it has this error in the browser console
```
Uncaught ReferenceError: process is not defined
    at root.jsx:26:16
```
![image](https://user-images.githubusercontent.com/8152024/225130877-1f25117e-b8db-42ac-bb63-c09f7ff8aeae.png)
That error prevents me from using for example useEffect() hook
That's why I had to try to use the function inside the loader()

**Comment by anakinsolo** [comment]
> @anakinsolo that's interesting. Because if the approach doesn't work at all and the process is not defined "always", the content shouldn't be displayed. But the connection to the Storyblok space is happening and the content is being retrieved. Maybe the statement is running more than once? Something to investigate related to Remix way of working? 🤔

@fgiuliani yes, I was thinking it's something Remix related. Basically, it might be something related to the way Remix bundle their JS into server and client files. But since I am pretty new and I do not know how it works under the hood, I just ask around for help. 

 But unfortunately, most of the time it's either there are people who use Remix but do not use Storyblok or vice versa

**Comment by anakinsolo** [comment]
> @anakinsolo I have created a starter Remix Storyblok Tailwind that you can find here https://github.com/alexadark/storyblok-remix-tailwind-starter Then env vars are working and you can see all the implementation in the root.jsx file These are the important parts Check if we are on the server or client
> 
> ```
> const isServer = typeof window === "undefined";
> 
> //We need to check if we are on the server or client to get the correct env variable
> const accessToken = isServer
>   ? process.env.STORYBLOK_PREVIEW_TOKEN
>   : window.env.STORYBLOK_PREVIEW_TOKEN;
> ```
> 
> Pass the token to storyblok init
> 
> ```
> storyblokInit({
>   accessToken,
>   use: [apiPlugin],
>   components,
> });
> ```
> 
> Return ENV for the client from the root loader
> 
> ```
> export const loader = async () => {
>   return json({
>     env: {
>       STORYBLOK_PREVIEW_TOKEN: process.env.STORYBLOK_PREVIEW_TOKEN,
>     },
>   });
> };
> ```
> 
> Put ENV on window - This is how we hand off the values from the server to the client. Make sure to put this before
> 
> ```
> <script
>           dangerouslySetInnerHTML={{
>             __html: `window.env = ${JSON.stringify(env)}`,
>           }}
>         />
>         ```
>  That's it and all should work!
>  Hope it helps!
>         
> ```

Hi,

Thank you for reply. This is interesting to see. Is there any case where the accessToken is called from server?

**Comment by schabibi1** [comment]
I remember that @anakinsolo was trying out with TypeScript approach.
If you get `ReferenceError: env is not defined`, you can find the solution to [this issue](https://github.com/alexadark/storyblok-remix-tailwind-starter/issues/1). 

[Here](https://github.com/schabibi1/remix-env-var-test)'s the TypeScript version of the super minimum starter with Storyblok & Remix if you want to fork and try the TS version.

**Comment by schabibi1** [comment]
@anakinsolo [Storyblok Content Deliver API](https://www.storyblok.com/docs/api/content-delivery/v2) is related to the accessToken (i.e. [preview API key token](https://www.storyblok.com/docs/guide/essentials/accessing-data)), and it is for interacting securely with our API from a client-side web application.

So, I would say usually called from client-side.

FYI, technically, `const accessToken = process.env.STORYBLOK_API_TOKEN;` loads content, but it disables the real-time editing feature from what I tested.

```javascript
const accessToken = process.env.STORYBLOK_API_TOKEN;

storyblokInit({
  accessToken,
  use: [apiPlugin],
  components,
});

export const loader = async () => {
  return json({
    env: {
      STORYBLOK_API_TOKEN: process.env.STORYBLOK_API_TOKEN,
    },
  });
};
```

`const accessToken = window.env.STORYBLOK_API_TOKEN;` returns ReferenceError for window.

**Comment by anakinsolo** [comment]
@alexadark @schabibi1 Hi, thanks for helping both of you. I can get it to work and have the preview showing in storyblok now. There is still small issue though. Because of typescript, I think.
![image](https://user-images.githubusercontent.com/8152024/230724101-8210a1f4-d974-47d3-b62d-7b4628066715.png)

**Comment by schabibi1** [comment]
@anakinsolo How does it change if you add `app/types/index.d.ts` file in this directory with the code below?
           
```javascript
/* eslint-disable no-var */

declare global {
  var env: any;
  var STORYBLOK_API_TOKEN: string;
}

export { };
```

**Comment by anakinsolo** [comment]
> @anakinsolo How does it change if you add `app/types/index.d.ts` file in this directory with the code below?
> 
> ```js
> /* eslint-disable no-var */
> 
> declare global {
>   var env: any;
>   var STORYBLOK_API_TOKEN: string;
> }
> 
> export { };
> ```

ah yea, thanks for the comment. I did the exact same thing a couple of days after I posted the previous question
