### ISSUE TITLE
A few type issues when switching to TypeScript

### ISSUE THREAD

**Issue by danspratling** [storyblok/storyblok-react#471]
## Expected Behavior

ISbStoriesParams types should === StoryblokBridgeConfigV2
ISbStoriesParams `is_startpage` should be a boolean

## Current Behavior

ISbStoriesParams has a type named `resolve_relations` which is [referenced in the docs](https://www.storyblok.com/docs/api/content-delivery/v2)
StoryblokBridgeConfigV2 has a type named `resolveRelations` which is identical to `resolve_relations` but this obviously creates a conflict.

`ISbStoriesParams.is_startpage` is a number (`0 | 1`), not a boolean (`true | false`) as [expected in the docs](https://www.storyblok.com/docs/api/content-delivery/v2)

## Suggestion

These are just two issues that I've run into when updating my types, but this indicates that there's a wider issue of types not correctly matching docs (or each other) which could lead to confusion or problems

**Comment by fgiuliani** [comment]
Hi @danspratling!
As those types are defined in `storyblok/js`, a core library from which the React SDK inherits certain logic, I created an issue on the repository of that library and will keep track of the changes there:

https://github.com/storyblok/storyblok-js/issues/271

We are already working on implementing those changes. Will keep updated on that other GitHub issue.

Closing this issue so we don't mix the topics.

Thank you!
