### ISSUE TITLE
getStories Response missing Total and perPage Props after Update from 2.0.15 to v2.0.16

### ISSUE THREAD

**Issue by lx-maxhaslehner** [storyblok/storyblok-react#480]
[storyblokurl]: https://www.storyblok.com?utm_source=github.com&utm_medium=issue-template

After updating Storyblok/react from Version 2.0.15 to 2.0.16, the "total" and "perPage" properties are missing on the storyblokApi.getStories response. 

`
let newsParams: any = {
        version: version,
        language: language,
        resolve_links: "url",
        by_slugs: folderslug + "/*",
        per_page: pageSize,
        page: pageIndex,
      };
await storyblokApi.getStories(newsParams);
`

## Expected Behavior

Provide the properties "total" and "perPage" again just like in the Version v2.0.15

![Bildschirmfoto 2023-03-30 um 14 07 23](https://user-images.githubusercontent.com/119567022/228837967-01e9058f-a8fe-46cd-b111-934de8fac95e.png)

## Current Behavior

Properties are not returned and can not be used to examine how many elements have to be fetched. 

![Bildschirmfoto 2023-03-30 um 14 06 42](https://user-images.githubusercontent.com/119567022/228838109-f23afcf7-ebcd-4c16-814e-27d79d4bdaa3.png)

## Steps to Reproduce

1. Import getStoryblokApi 
`import { getStoryblokApi } from "@storyblok/react";
`
2. Fetch multiple stories from folder with pagination params
`let newsParams: any = {
        version: version,
        language: language,
        resolve_links: "url",
        by_slugs: folderslug + "/*",
        per_page: pageSize,
        page: pageIndex,
      };
await storyblokApi.getStories(newsParams);`
3. Check the response provided by .getStories

**Comment by Barokai** [comment]
seems to be fixed with 2.0.17 (includes updated dependency https://github.com/storyblok/storyblok-js-client/releases/tag/v5.10.2)

**Comment by lx-maxhaslehner** [comment]
Update: closing this issue since version 2.0.17 fixes this problem.

**Comment by fgiuliani** [comment]
I came here to let you know that we just released a new version of the SDK that may fix the issue, but looks like you already saw it 😅 

Thank you @lx-maxhaslehner @Barokai!
