### ISSUE TITLE
rsc typings not available

### ISSUE THREAD

**Issue by mkuczera** [storyblok/storyblok-react#570]
### Description

When using the import statements of your next.js 13 example (https://www.storyblok.com/tp/add-a-headless-cms-to-next-js-13-in-5-minutes#creating-components-in-the-next-js-app) typescript complains about the not found module at the "@storyblok/react/rsc" path.

### Suggested solution or improvement

For a local workaround i created a .d.ts file

```
declare module "@storyblok/react/rsc" {
  export * from "@storyblok/react"
}
```

Out of the box typings would be perfect because i just assume right now that every component is also available in the rsc context.

### Validations

- [X] Follow our [Code of Conduct](https://www.storyblok.com/trust-center#code-of-conduct?utm_source=github.com&utm_medium=readme&utm_campaign=storyblok-js-client)

**Comment by ui-jb** [comment]
I have a similar issue with `@storyblok/react/bridge-loader`

**Comment by quocanh944** [comment]
I have a similar issue with `@storyblok/react/story`

**Comment by AleksandrRyb** [comment]
yep, there is the same issue with rsc

**Comment by alexjoverm** [comment]
Hey all, that's actually more an issue on the Next 13 starter template. If you change `"moduleResolution": "nodenext"` (or `node16` in your `tsconfig.json` it should work.

We're evaluating with Next.js team if they can change that in the template

**Comment by ui-jb** [comment]
> Hey all, that's actually more an issue on the Next 13 starter template. If you change `"moduleResolution": "nodenext"` (or `node16` in your `tsconfig.json` it should work.
> 
> We're evaluating with Next.js team if they can change that in the template

This did the trick!

**Comment by fgiuliani** [comment]
Hello everyone! Just a quick update:

I created a PR on Next.js` create-next-app` starter template, that is being reviewed and probably will get merged soon:
https://github.com/vercel/next.js/pull/51957

**Comment by fgiuliani** [comment]
Closing this issue as the Vercel team merged the PR that changes the `moduleResolution` value on `tsconfig.json` for the `create-next-app` starter:
https://github.com/vercel/next.js/pull/51957
