### ISSUE TITLE
useStoryblokState stopped live updating content in 2.1.5 

### ISSUE THREAD

**Issue by ps-bzaragoza** [storyblok/storyblok-react#580]
### Describe the issue you're facing

When editing content in Storyblok, the preview iframe stopped updating its contents when updating to @storyblok/react `2.1.5`. This feature still works in `2.1.4`, which makes me suspect [this PR](https://github.com/storyblok/storyblok-react/pull/544) might be the cause of it.  The _window_ object is being accessed in [useStoryblokBridge](https://github.com/storyblok/storyblok-js/blob/main/lib/index.ts) and it needs to be defined. I believe this is what _useEffect_ was needed for.

I'm using Pages Router, following the implementation from the [README](https://github.com/storyblok/storyblok-react#nextjs-using-pages-router).

### Reproduction

-

### System Info

```shell
node 18.16.0, @storyblok/react 2.1.5
```

### Used Package Manager

yarn

### Validations

- [X] Follow our [Code of Conduct](https://www.storyblok.com/trust-center#code-of-conduct?utm_source=github.com&utm_medium=readme&utm_campaign=storyblok-js-client)

**Comment by fgiuliani** [comment]
Hi @ps-bzaragoza thanks for your input.
I just tested the SDK with the [Next.js playground](https://github.com/storyblok/storyblok-react/tree/main/playground-next) we have in this repository and everything is working as expected.

Can you share more details or probably a specific error you get so we can tailor the error and try to reproduce it?

**Comment by lillheaton** [comment]
I can also confirm this. Updating to 2.1.5 breaks live edit

**Comment by fgiuliani** [comment]
@ps-bzaragoza @lillheaton we just released a new version of the SDK (2.1.6) reverting the changes applied on the PR that you pointed out.

Can you check if the live editing is working now for you?

**Comment by ps-bzaragoza** [comment]
I can confirm live edit works again in `2.1.6`. Thanks!
