### ISSUE TITLE
Server-side Exception with Next.js 13 and Storyblok in Production

### ISSUE THREAD

**Issue by bencehusi** [storyblok/storyblok-react#718]
### Describe the issue you're facing

I have built a Next.js 13 application using Storyblok as the headless CMS. While the app works perfectly fine in development mode, it throws a server error a **few minutes after** being deployed to production (meaning it works alright for a little while). The error message I get is `Application error: a server-side exception has occurred` - more details below.

#### Environment:

- Next.js 13 "next": "^13.4.8"
- "@storyblok/react": "^2.4.4" (using `getStoryblokApi` from `@storyblok/react/rsc`)

#### Steps to Reproduce:

1. Build the Next.js 13 app with Storyblok as per this [tutorial](https://www.storyblok.com/tp/add-a-headless-cms-to-next-js-13-in-5-minutes).
2. Instead of the static page, add dynamic routes [...slug] to handle arbitrary content from Storyblok
3. Build and run the app locally (`npm run build` then `npm run start`) or deploy the application to a production environment.
4. After a few minutes of successful running, the application crashes with a server error.

#### Expected Behavior:

The application should run smoothly in production as it does in development.

#### Actual Behavior:

A server-side exception occurs a few minutes after the app starts running in production.

#### Error Logs:

```
TypeError: Cannot read properties of undefined (reading 'HelpCollection')
[application-name-redacted] [2023-08-31 09:19:16]     at i (/workspace/.next/server/chunks/9221.js:4274:144)
[application-name-redacted] [2023-08-31 09:19:16]     at /workspace/.next/server/chunks/9221.js:4251:15
[application-name-redacted] [2023-08-31 09:19:16]     at T (/workspace/.next/server/chunks/7122.js:53810:52)
[application-name-redacted] [2023-08-31 09:19:16]     at Xa (/workspace/.next/server/chunks/7122.js:53887:21)
[application-name-redacted] [2023-08-31 09:19:16]     at Object.toJSON (/workspace/.next/server/chunks/7122.js:53701:20)
[application-name-redacted] [2023-08-31 09:19:16]     at stringify (<anonymous>)
[application-name-redacted] [2023-08-31 09:19:16]     at hb (/workspace/.next/server/chunks/7122.js:54097:9)
[application-name-redacted] [2023-08-31 09:19:16]     at eb (/workspace/.next/server/chunks/7122.js:53996:29)
[application-name-redacted] [2023-08-31 09:19:16]     at Timeout._onTimeout (/workspace/.next/server/chunks/7122.js:53832:16)
[application-name-redacted] [2023-08-31 09:19:16]     at listOnTimeout (node:internal/timers:559:17)
```

(Do note, `HelpCollection` is the name of my component for a content type, which does exist and is passed to the components props in the `storyblokInit` call - and as said, it works in development mode and in production for a couple of minutes.)

#### The code behind the error logs

I've managed to investigate the piece of code that crashes:

```javascript
// CONCATENATED MODULE: ./node_modules/@storyblok/react/dist/index2.mjs
const index2_b = ()=>(e || console.error("You can't use getStoryblokApi if you're not loading apiPlugin."), e), c = (o)=>(t = o, t), i = (o)=>t[o] ? t[o] : (console.error(`Component ${o} doesn't exist.`), !1), k = ()=>r, index2_m = ()=>l, p = (o = {})=>{
    const { storyblokApi: n } = de(o);
    e = n, t = o.components, r = o.enableFallbackComponent, l = o.customFallbackComponent;
};
```

I think this is the line here: https://github.com/storyblok/storyblok-react/blob/5ef81ebfdcf7f6249f9563030f3d8b22b7574d81/lib/common/index.ts#L25C6-L25C6

So apparently the `componentsMap` becomes undefined after the application was running for a couple of minutes. I couldn't narrow it down any more specific wheter it's a certain amount of time, or certain activities on the server that brings this bug to surface.

---

Any help diagnosing and fixing this issue would be greatly appreciated. Thank you!

### Reproduction

https://github.com/storyblok/next.js-13-boilerplate

### Steps to reproduce

1. Build the Next.js 13 app with Storyblok as per this [tutorial](https://www.storyblok.com/tp/add-a-headless-cms-to-next-js-13-in-5-minutes).
2. Instead of the static page, add dynamic routes [...slug] to handle arbitrary content from Storyblok
3. Build and run the app locally (`npm run build` then `npm run start`) or deploy the application to a production environment.
4. After a few minutes of successful running, the application crashes with a server error.

### System Info

```shell
ystem:
    OS: macOS 13.4.1
    CPU: (10) arm64 Apple M1 Pro
    Memory: 259.95 MB / 32.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 20.3.1 - ~/.nvm/versions/node/v20.3.1/bin/node
    npm: 9.6.7 - ~/.nvm/versions/node/v20.3.1/bin/npm
  Browsers:
    Chrome: 116.0.5845.140
    Safari: 16.5.2
```

### Used Package Manager

npm

### Validations

- [X] Follow our [Code of Conduct](https://www.storyblok.com/trust-center#code-of-conduct?utm_source=github.com&utm_medium=readme&utm_campaign=storyblok-js-client)

**Comment by fgiuliani** [comment]
Hi @bencehusi!

Did this happen to you in more than one project?
I will discuss this with the team, and see if there are other users that experienced the same issue.

**Comment by bencehusi** [comment]
I migrated only one app so far!

Meanwhile, I've reverted to using my own implementation for the component map.

Leaving the snippet here should anyone else have the same issue:

```typescript
// /components/helpers/StoryblokComponent/StoryblokComponent.tsx

export function StoryblokComponent({ blok, ...rest }: any) {
  if (!blok) return <>Please provide a blok element.</>;

  const componentMap: any = {
    // ... list your imported components here...
  };

  if (typeof componentMap[blok.component] !== 'undefined') {
    const Component = componentMap[blok.component];
    return <Component blok={blok} {...rest} />;
  }
  return <>Component {blok.component} doesnt exist.</>;
}

```

**Comment by fgiuliani** [comment]
Hi @bencehusi, thanks for sharing!
About the approach you shared, did it fix the issue for you?

**Comment by bernhardw** [comment]
I get the same error message in production on Vercel with Next.js 13 and up-to-date Storyblok packages:

```
You can't use getStoryblokApi if you're not loading apiPlugin.
TypeError: Cannot read properties of null (reading 'get')
    at fetchStory (/var/task/.next/server/app/[locale]/[[...slug]]/page.js:1691:41)
    at PageTemplate (/var/task/.next/server/app/[locale]/[[...slug]]/page.js:1708:25)
    at preloadComponent (/var/task/node_modules/next/dist/server/app-render/preload-component.js:23:22)
    at /var/task/node_modules/next/dist/server/app-render/app-render.js:615:101
    at async createComponentTree (/var/task/node_modules/next/dist/server/app-render/app-render.js:615:29)
    at async /var/task/node_modules/next/dist/server/app-render/app-render.js:543:91
    at async Promise.all (index 0)
    at async createComponentTree (/var/task/node_modules/next/dist/server/app-render/app-render.js:501:38)
    at async /var/task/node_modules/next/dist/server/app-render/app-render.js:667:56
```

Although it happens **after every (re-)deploy on first visit**. It works after reloading and subsequent visits. 

Maybe Storyblok isn't initialized yet when first calling `getStoryblokApi`? I initialize Storyblok inside my root layout and call `getStoryblokApi` in a page template.

**Comment by safakggm** [comment]
Hi @bernhardw , because the getStoryblokApi function is created on the client side, we cannot access this function in SSR.
You can solve this problem with the solution below.

```
export async function getStaticProps({ params }) {
 ....

  let storyblokApi = getStoryblokApi()
  if (!storyblokApi) {
    storyblokInit({
      accessToken: ...,
      use: [...],
      components: ...,
    })
    storyblokApi = getStoryblokApi()
  }
  const { data } = await storyblokApi.get(
    slug,
    params
  )
  
......
}
```

**Comment by bernhardw** [comment]
@safakggm Thanks, but I'm using App Router and initializing (in layout.tsx) and using (in page.tsx) `getStoryblokApi()` on the server.

**Comment by safakggm** [comment]
@bernhardw, next.js is passed to the layout after the page is created. This means that the page is created in the SSR before the layout. The same applies to the "App Router".

**Comment by bernhardw** [comment]
@safakggm Thanks, I tried to find any info on the order in which the files are executed, but could not find anything. 

Some simple console.log's indicate that layout.tsx is run before page.tsx and even the official Storyblok guide on Next.js 13 initializes Storyblok in layout.tsx: https://www.storyblok.com/tp/add-a-headless-cms-to-next-js-13-in-5-minutes#connecting-to-storyblok

What do you suggest?

**Comment by safakggm** [comment]
@bernhardw I think this is a correct use. This is This way you can run the Storyblok when it is not initialized, but I can't test it because I don't use the route app in Next.js 13.

```
import { getStoryblokApi } from '@storyblok/react/rsc'
import { storyblokInit } from './storyblokInit'

export function getStoryblok() {
  let storyblok = getStoryblokApi()

  if (!storyblok) {
    storyblokInit()
    storyblok = getStoryblokApi()
  }

  return storyblok
}

```

**Comment by bernhardw** [comment]
@safakggm Yes that works, but it - presumably - bundles my Storyblok components and bloats my initial page load, like the screenshots show.

If anyone has the same problem, I have now removed the `apiPlugin` from the initialization of [@storyblok/react](https://github.com/storyblok/storyblok-react) and use the [storyblok-js-client](https://github.com/storyblok/storyblok-js-client) directly when needing to fetch data from Storyblok. This works and doesn't bloat my JavaScript files.

**Comment by fgiuliani** [comment]
Hi @bernhardw did you take a look at our tutorial on how to use the React SDK with Next.js 13?
https://www.storyblok.com/tp/add-a-headless-cms-to-next-js-13-in-5-minutes

https://github.com/storyblok/storyblok-react#nextjs-using-app-router---live-editing-support

Also, the SDK offers a setComponents function to dynamically set the list of components to match with Storyblok:
https://github.com/storyblok/storyblok-react#3-adding-components-per-page

**Comment by wa1id** [comment]
> I get the same error message in production on Vercel with Next.js 13 and up-to-date Storyblok packages:
> 
> ```
> You can't use getStoryblokApi if you're not loading apiPlugin.
> TypeError: Cannot read properties of null (reading 'get')
>     at fetchStory (/var/task/.next/server/app/[locale]/[[...slug]]/page.js:1691:41)
>     at PageTemplate (/var/task/.next/server/app/[locale]/[[...slug]]/page.js:1708:25)
>     at preloadComponent (/var/task/node_modules/next/dist/server/app-render/preload-component.js:23:22)
>     at /var/task/node_modules/next/dist/server/app-render/app-render.js:615:101
>     at async createComponentTree (/var/task/node_modules/next/dist/server/app-render/app-render.js:615:29)
>     at async /var/task/node_modules/next/dist/server/app-render/app-render.js:543:91
>     at async Promise.all (index 0)
>     at async createComponentTree (/var/task/node_modules/next/dist/server/app-render/app-render.js:501:38)
>     at async /var/task/node_modules/next/dist/server/app-render/app-render.js:667:56
> ```
> 
> Although it happens **after every (re-)deploy on first visit**. It works after reloading and subsequent visits.

Having same error on nextjs with this additional error as well:
```
app/[locales]/[...slug]/page.tsx (33:10) @ data
 ⨯ TypeError: Cannot destructure property 'data' of '(intermediate value)' as it is undefined.
    at Page (./app/[locales]/[...slug]/page.tsx:32:13)
  31 |   let slug = params.slug ? params.slug.join('/') : 'home'
  32 | 
> 33 |   const { data }: ISbStory = await fetchData(slug)
     |          ^
  34 | 
  35 |   return (
  36 |     <>
```

**Comment by fgiuliani** [comment]
Hi @wa1id can you show the code of your `fetchData` method, to see what it is returning?
