### ISSUE TITLE
live edit mode not working with react hooks 

### ISSUE THREAD

**Issue by Britnell** [storyblok/storyblok-react#724]
### Describe the issue you're facing

Hey, 
i'm having some issues with the hooks - which looking at other issues you kind of know about 
 from this issue  - https://github.com/storyblok/storyblok-react/issues/113
it was closed by the dev who opened it but it seems to me he jsut found a workaround, and the issue still persists in the library. you yourself said someone should open a new issue, so im doing that. however i dont have a reproduction, but you already know what this is about ...

i was going to create my own custom hook / bridge but was told by your support to to just use the hook from the libary...
the solution in issue #113 to add a third preview parameter to useStoryblokState is not actually implemented yet either ...

and when rolling my own i have no idea if i should use the older storyblock-client lib or the newer https://www.storyblok.com/mp/announcing-storyblok-js 
it doesnt say much about either of those if they are still working or what can should be used ... somehow there's a ton of options, but for none of them there's working straightforward code ...

i'm tempted to go with the solution in this issue https://github.com/storyblok/storyblok-react/issues/156 
as he says, i thought you had reduced some of the original boiler plate of custom hooks with those new libraries... quite disappointing, and really confusing as waste so much time testing those out ... 

do you have an example of best practices for custom react hooks from storyblok-client ? 

### Reproduction

none

### Steps to reproduce

storyblokInit({
  accessToken: 'token',
  use: [apiPlugin],
  components: {},
  bridge: true,
  apiOptions: {
    cache: {
      type: 'none',
      clear: 'auto',
    },
  },
})

export default function Page(){
  story = useStoryblokState(story, {},)
  ...
}

next12 , react 18, SSR page

### System Info

```shell
System:
    OS: Linux 6.2 Ubuntu 22.04.2 LTS 22.04.2 LTS (Jammy Jellyfish)
    CPU: (8) x64 11th Gen Intel(R) Core(TM) i7-1185G7 @ 3.00GHz
    Memory: 8.14 GB / 15.33 GB
    Container: Yes
    Shell: 5.1.16 - /bin/bash
  Binaries:
    Node: 18.17.1 - /usr/local/bin/node
    Yarn: 1.22.19 - /usr/local/bin/yarn
    npm: 8.19.2 - /usr/local/bin/npm
    pnpm: 8.6.2 - /usr/local/bin/pnpm
  Browsers:
    Brave Browser: 115.1.56.14
    Chrome: 114.0.5735.198
    Chromium: 116.0.5845.140
```

### Used Package Manager

npm

### Validations

- [X] Follow our [Code of Conduct](https://www.storyblok.com/trust-center#code-of-conduct?utm_source=github.com&utm_medium=readme&utm_campaign=storyblok-js-client)

**Comment by fgiuliani** [comment]
Hi @Britnell,

What issue are you exactly facing? I'm not sure I'm following.
We didn't add a `preview` parameter because now that logic is managed from the storyblokInit function, where you can enable or disable the bridge based on the environment you are running your website:

https://github.com/storyblok/storyblok-react#initialization

https://github.com/storyblok/storyblok-react/blob/main/lib/common/client.ts#L12

If you want to create your own React hook, you can see this example we have from an implementation that is previous to the creation of the React SDK:

https://github.com/storyblok/talk-from-zero-to-nextjs-hero/blob/main/lib/storyblok-hook.js

**Comment by Britnell** [comment]
Hey,  thanks for reply. 
issue is that live edit isnt working, sounds similar to sendy34 & annarhughes .
* preview mode works fine, i get green boxes to select element,
* 'save' event works, hitting save refreshes the page w new content
* but live edit doesnt work.

also im not sure about enabling / disabling the bridge based on environment, as discussed [here too](https://github.com/storyblok/storyblok-react/issues/113#issuecomment-1179513633) I dont want to need a second deploy just for live edit mode, to me the power is that i can see & edit changes in the live site, and loading the code for the bridge dynamically is easily done. 
do i understand correctly then that the lib is not meant tat way? if i enable the bridge in apiOptions, then the code for the bridge will always be loaded? or is it only loaded when it is in iframe and communicating with SB editor?

not sure what the #initialization link is telling me, you can see my init code above, doesnt work despite enabling bridge. : /
any other pointers? or shall i just roll my own. when i saw this library i thought the point was to no longer need to roll your own, whats the point of this library then if the hooks dont work.

**Comment by Britnell** [comment]
in the storyblok/react repo i can't see a working version for bridge / live edit mode, it would be great if there was just a working example of this on stackblitz, i couldnt get it to work and from issues it seems several others couldnt either. it would be good to see what the implementation is supposed to look like, might be more useful than me setting up a demo on stackblitz of my example thats not working ... the only code needed for that is the storyblokInit() i shared above...

**Comment by Britnell** [comment]
actually the demo custom hook storyblok-hook.js you shared gives me a ts error, does this def work?
`Property 'accessToken' is private and only accessible within class 'Storyblok'.ts(2341)`
on line
`script.src = `https://app.storyblok.com/f/storyblok-latest.js?t=${Storyblok.accessToken}` `

**Comment by Britnell** [comment]
just tried the custom hook and live edit mode doenst work either.
preview works, i can click on components to open them in editor, 
and hitting save refreshes page with edited content, but still no live edit ...

any other pointers?

**Comment by Britnell** [comment]
Hey @arorachakit , thanks for the reply, 

i finally had time to setup a test and it worked! so i found  the top-level blok fields are actually updating with live mode, but the main content of the page isn't. 
I can't share the code repo unfortunately , but  that means the bridge is working and the problem is in my code, apologies! 
we're combining a bunch of data so probably something is going wrong there.

Closing this, thanks !

**Comment by Britnell** [comment]
oh can i check though, when bridge mode is enabled `{ bridge: true }` is the code for bridge always imported or is that done conditionally ? when trying to see the code of the hook vs code just shows me the file with the types

**Comment by arorachakit** [comment]
Hey @Britnell  - The bridge is only loaded when it see a couple of parameters that make sure it is inside the visual editor and also at the specific URL you are trying the access so that it doesn't load twice if you're even using a hook that initialises it.

To see the code, you can actually clone this repo and see it. This is build on top of https://github.com/storyblok/storyblok-js, so you can see that as well.

**Comment by Britnell** [comment]
hey @arorachakit , thanks for the reply!
just to make sure we're talking about the same thing, sure the bridge is only loaded once, but i mean is the code for the bridge always loaded and included in the bundle, or is the bridge script loaded conditionally like in this custom hook? 
https://github.com/storyblok/talk-from-zero-to-nextjs-hero/blob/main/lib/storyblok-hook.js#L38
