### ISSUE TITLE
NextJS App Router - RSC types won't load

### ISSUE THREAD

**Issue by xRitsu** [storyblok/storyblok-react#751]
### Describe the issue you're facing

When importing `@storyblock/react/rsc` using Typescript, the IDE will say that the package's type declaration files could not be found and therefore, it will fail to compile. This makes it impossible to use Storyblok in any TS application using the new NextJS App Router.
![Screenshot_1](https://github.com/storyblok/storyblok-react/assets/26928100/6c3328bf-0556-45ef-a935-62bf6898f43d)

### Reproduction

https://github.com/storyblok/next.js-13-boilerplate

### Steps to reproduce

1. Download the reproduction repository and `npm install`.
2. Change `layout.js` to `layout.ts`.
3. The error should come up.

### System Info

```shell
Storyblok package version: 2.1.0 ~ 2.4.7 (latest)

System:
    OS: Windows 10 10.0.22621
    CPU: (12) x64 Intel(R) Core(TM) i5-10400F CPU @ 2.90GHz
    Memory: 3.97 GB / 15.94 GB
  Binaries:
    Node: 20.7.0 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.19 - ~\AppData\Roaming\npm\yarn.CMD
    npm: 10.1.0 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Edge: Spartan (44.22621.2283.0), Chromium (117.0.2045.41)
    Internet Explorer: 11.0.22621.1
```

### Used Package Manager

npm

### Validations

- [X] Follow our [Code of Conduct](https://www.storyblok.com/trust-center#code-of-conduct?utm_source=github.com&utm_medium=readme&utm_campaign=storyblok-js-client)

**Comment by fgiuliani** [comment]
Hi @xRitsu! That's the intended usage. You can read more about that here:

https://github.com/storyblok/storyblok-react/issues/613#issuecomment-1683077548
https://github.com/storyblok/storyblok-react/issues/570#issuecomment-1650486695
