### ISSUE TITLE
Broken links in README.md

### ISSUE THREAD

**Issue by marcnewport** [storyblok/storyblok-react#786]
### Describe the issue you're facing

Hey there 👋

While working on a project I came across a broken link for the base RichTextSchema. So I thought I'd fix it! And then found another broken link to the contributors doc 🙃 I've updated both links in a PR here https://github.com/storyblok/storyblok-react/pull/785

### Reproduction

https://github.com/storyblok/storyblok-react

### Steps to reproduce

Go to the github repo page and view README.md

### System Info

```shell
n/a
```

### Used Package Manager

npm

### Validations

- [X] Follow our [Code of Conduct](https://www.storyblok.com/trust-center#code-of-conduct?utm_source=github.com&utm_medium=readme&utm_campaign=storyblok-js-client)

**Comment by fgiuliani** [comment]
Thanks for your contribution @marcnewport!
PR already merged 😄
