### ISSUE TITLE
Cannot find module '@storyblok/react/rsc' or its corresponding type declarations.ts(2307)

### ISSUE THREAD

**Issue by duddelito** [storyblok/storyblok-react#907]
### Describe the issue you're facing

In my Typescript Next.js app I am unable to 
import from @storyblok/react/rsc like below:

`import { storyblokInit, apiPlugin } from '@storyblok/react/rsc';`

and am getting 
`Cannot find module '@storyblok/react/rsc' or its corresponding type declarations.ts(2307)`

If I in my tsconfig.json switch and go from:
`    "module": "esnext",
    "moduleResolution": "node",`
to
`    "module": "esnext",
    "moduleResolution": "bundler",`
or to
`    "module": "NodeNext",
    "moduleResolution": "NodeNext",`
    
I can import it without errors but will then get multiple other typescript problems in my project due to components not being imported correctly.

I even tried the `full-server-side` branch in https://github.com/storyblok/next.js-13-boilerplate/tree/full-server-side and as soon as I go over to using Typescript I am getting the same problems in this project.
![Screenshot 2024-01-16 at 13 40 41](https://github.com/storyblok/storyblok-react/assets/18570347/9b374bd5-57d5-4c7e-952a-66d76754758d)

### Reproduction

https://github.com/storyblok/next.js-13-boilerplate/tree/full-server-side

### Steps to reproduce

Clone down https://github.com/storyblok/next.js-13-boilerplate/tree/full-server-side and rename layout.js to layout.tsx and page.js to page.tsx and run yarn dev or npm run dev. 

### System Info

```shell
System:
    OS: macOS 13.2.1
    CPU: (10) arm64 Apple M1 Pro
    Memory: 66.63 MB / 16.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 18.17.1 - ~/.volta/tools/image/node/18.17.1/bin/node
    Yarn: 1.22.19 - ~/.volta/tools/image/yarn/1.22.19/bin/yarn
    npm: 9.6.7 - ~/.volta/tools/image/node/18.17.1/bin/npm
    pnpm: 8.6.12 - ~/.nvm/versions/node/v16.17.0/bin/pnpm
  Browsers:
    Chrome: 120.0.6099.216
    Safari: 16.3
```

### Used Package Manager

npm

### Validations

- [X] Follow our [Code of Conduct](https://www.storyblok.com/trust-center#code-of-conduct?utm_source=github.com&utm_medium=readme&utm_campaign=storyblok-js-client)

**Comment by dariusrosendahl** [comment]
This is working for me with Typescript 5.0+.

`tsconfig.json`:

```
"module": "esnext",
"moduleResolution": "Bundler",
```

**Comment by duddelito** [comment]
> This is working for me with Typescript 5.0+.
> 
> `tsconfig.json`:
> 
> ```
> "module": "esnext",
> "moduleResolution": "Bundler",
> ```

Yes that's what I said in the issue.

**Comment by dariusrosendahl** [comment]
> Yes that's what I said in the issue.

Are you sure? I see these combinations but not `esnext` + `Bundler`:

> If I in my tsconfig.json switch and go from:
    "module": "esnext", "moduleResolution": "node",
to
    "module": "bundler", "moduleResolution": "node",
or to
    "module": "NodeNext", "moduleResolution": "NodeNext",

That is really the only combination that worked for me. 
I had to fix a few other typescript errors in my projects but it's all working now on multiple projects.

**Comment by duddelito** [comment]
> > Yes that's what I said in the issue.
> 
> Are you sure? I see these combinations but not `esnext` + `Bundler`:
> 
> > If I in my tsconfig.json switch and go from:
> > "module": "esnext", "moduleResolution": "node",
> > to
> > "module": "bundler", "moduleResolution": "node",
> > or to
> > "module": "NodeNext", "moduleResolution": "NodeNext",
> 
> That is really the only combination that worked for me. I had to fix a few other typescript errors in my projects but it's all working now on multiple projects.

I realise now when I wrote the issue I put "bundler" in the wrong place. I've edited the issue now.

Anyways it would be nice if @storyblok/react/rsc could work with 
"module": "esnext", "moduleResolution": "node",

If I import @storyblok/react it works without problems, but when adding /rsc is when the issue appears.

**Comment by arorachakit** [comment]
Hey @duddelito ! I am glad it is working for you now.
To use our RSC version of React SDK you need a typescript version with support for multi-libs. That’s why we suggest module resolution set to bundler (or nodenext). 
FYI, node refers to Node 14 which is been largely unsupported and deprecated for a while.

I see that it is already solved for you, so I will close the issue but feel free to open another one if there is anything else :)
